//! Strict stage-archive import and export without source-byte fallbacks.
//!
//! The archive container is retained only as structured RARC metadata. Every
//! child payload is consumed during import and must be regenerated by one of
//! the semantic format variants before export can succeed.
//!
//! "Source-free" means no original file/archive buffer and no opaque fallback.
//! Native authored encodings such as GX texture blocks, float bit patterns,
//! message controls, and ordered scalar banks remain semantic resource data;
//! without those values no level, let alone an exact one, can be rebuilt.

use serde::{Deserialize, Serialize};
use sms_formats::{
    BasFile, BmgFile, BmpFile, BtiFile, ColFile, FormatError, J3dAnimationRebuildDocument,
    J3dAnimationSection, J3dRebuildDocument, JDramaDocument, JDramaField, JDramaFieldValue,
    JDramaRecord, JDramaRecordPayload, JDramaTransform, JpaxDocument, MarioRecordBundle,
    MarkerTextFile, PrmFile, RalDocument, RarcArchive, RarcBuilder, RarcDocument,
    ReplayLinkDocument, SpcDocument, Yaz0Document, YmpDocument,
};

use crate::{Result, SceneError};

const SEMANTIC_STAGE_DOCUMENT_KIND: &str = "sms-semantic-stage-archive";
const SEMANTIC_STAGE_DOCUMENT_VERSION: u32 = 1;

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct SemanticStageDocumentEnvelope {
    kind: String,
    format_version: u32,
    archive: SourceFreeStageArchive,
}

/// A complete archive whose child resources are owned as semantic documents.
///
/// Import is deliberately strict: an asset with no source-free codec rejects
/// the archive instead of being cached as an opaque byte vector. This makes it
/// impossible for a successful rebuild to silently fall back to source bytes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceFreeStageArchive {
    archive: RarcDocument,
    compression: Option<StageCompression>,
    resources: Vec<StageResource>,
    #[serde(default)]
    origin: StageOrigin,
}

/// Editor provenance for a detached stage archive. The binary RARC format has
/// no field for this metadata, so a binary reimport is correctly classified as
/// imported while semantic project documents retain their authored target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum StageOrigin {
    #[default]
    ImportedArchive,
    Blank {
        target_slot: String,
        preset_version: u32,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum StageCompression {
    Yaz0 { reserved: [u8; 8] },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StageResource {
    pub raw_path: Vec<u8>,
    pub document: StageResourceDocument,
}

/// Semantic address and editable transform for an actor record. The address is
/// a child-index path through the JDrama group tree, independent of source byte
/// offsets. Insertions/removals invalidate later sibling paths, so callers must
/// apply removals deepest-first and refresh addresses after structural edits.
#[derive(Debug, Clone, PartialEq)]
pub struct StageObjectPlacement {
    pub raw_resource_path: Vec<u8>,
    pub record_path: Vec<usize>,
    pub type_name: String,
    pub name: String,
    pub transform: JDramaTransform,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum StageResourceDocument {
    Animation(Box<J3dAnimationRebuildDocument>),
    AnimationSound(BasFile),
    Bitmap(BmpFile),
    Collision(ColFile),
    Message(BmgFile),
    Marker(MarkerTextFile),
    Model(J3dRebuildDocument),
    Particle(JpaxDocument),
    PlayerReplay(MarioRecordBundle),
    Placement(JDramaDocument),
    PollutionMap(YmpDocument),
    Parameters(PrmFile),
    Rail(RalDocument),
    ReplayLinks(ReplayLinkDocument),
    Script(SpcDocument),
    Texture(BtiFile),
}

impl StageResourceDocument {
    /// Encodes this detached typed resource without consulting its source
    /// archive. Editor previews use this for project overlay resources that do
    /// not exist in the retail stage being edited.
    pub fn to_bytes(&self) -> sms_formats::Result<Vec<u8>> {
        encode_resource(self)
    }

    /// Parses one archive child according to its raw resource path into the
    /// same strict semantic representation used by stage archive import.
    pub fn parse_for_path(raw_path: &[u8], payload: &[u8]) -> sms_formats::Result<Self> {
        parse_resource(raw_path, payload)
    }
}

impl SourceFreeStageArchive {
    /// Creates an empty source-free stage archive with the canonical `scene`
    /// RARC root. Blank-stage authoring defaults to the dedicated `test11`
    /// target; callers may replace the provenance metadata before persistence.
    pub fn new() -> Result<Self> {
        Self::new_for_blank("test11", 1)
    }

    pub fn new_for_blank(target_slot: impl Into<String>, preset_version: u32) -> Result<Self> {
        Ok(Self {
            archive: RarcBuilder::new_scene().build()?,
            compression: None,
            resources: Vec::new(),
            origin: StageOrigin::Blank {
                target_slot: target_slot.into(),
                preset_version,
            },
        })
    }

    /// Imports a RARC or Yaz0-wrapped RARC and consumes every file payload.
    ///
    /// This constructor succeeds only when every child has a semantic writer.
    /// Unsupported resources are reported by exact archive path.
    pub fn parse(bytes: &[u8]) -> Result<Self> {
        let (compression, rarc_bytes) = if bytes.starts_with(b"Yaz0") {
            let Yaz0Document { reserved, data } = Yaz0Document::parse(bytes)?;
            (Some(StageCompression::Yaz0 { reserved }), data)
        } else {
            (None, bytes.to_vec())
        };

        // RarcArchive provides the validated, fully qualified raw paths. It is
        // an ingestion-only index and is dropped before this function returns.
        let index = RarcArchive::parse(&rarc_bytes)?;
        let file_paths = index
            .file_entries()
            .iter()
            .map(|entry| entry.raw_path.clone())
            .collect::<Vec<_>>();
        let mut archive = RarcDocument::parse(&rarc_bytes)?;
        drop(index);
        drop(rarc_bytes);

        let mut resources = Vec::with_capacity(file_paths.len());
        for raw_path in file_paths {
            let payload = archive.take_file_data(&raw_path)?;
            let document = parse_resource(&raw_path, &payload).map_err(|source| {
                SceneError::StageResource {
                    path: display_raw_path(&raw_path),
                    source,
                }
            })?;
            resources.push(StageResource { raw_path, document });
        }

        if archive
            .entries
            .iter()
            .any(|entry| !entry.is_directory() && entry.data.is_some())
        {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive",
                message: "a file payload remained cached after semantic import".to_string(),
            }));
        }

        Ok(Self {
            archive,
            compression,
            resources,
            origin: StageOrigin::ImportedArchive,
        })
    }

    pub fn origin(&self) -> &StageOrigin {
        &self.origin
    }

    pub fn set_origin(&mut self, origin: StageOrigin) {
        self.origin = origin;
    }

    pub fn compression(&self) -> Option<StageCompression> {
        self.compression
    }

    pub fn set_compression(&mut self, compression: Option<StageCompression>) {
        self.compression = compression;
    }

    pub fn resources(&self) -> &[StageResource] {
        &self.resources
    }

    pub fn resources_mut(&mut self) -> &mut [StageResource] {
        &mut self.resources
    }

    /// Serializes the detached typed archive document, not its source stream.
    /// Container file payload slots must remain empty; every child exists only
    /// as one of the semantic resource variants in `resources`.
    pub fn to_semantic_json(&self) -> Result<Vec<u8>> {
        self.validate_detached_state()?;
        Ok(serde_json::to_vec_pretty(&SemanticStageDocumentEnvelope {
            kind: SEMANTIC_STAGE_DOCUMENT_KIND.to_string(),
            format_version: SEMANTIC_STAGE_DOCUMENT_VERSION,
            archive: self.clone(),
        })?)
    }

    /// Loads a complete detached archive document and proves that it can be
    /// rebuilt and reparsed without consulting a retail archive.
    pub fn from_semantic_json(bytes: &[u8]) -> Result<Self> {
        let envelope: SemanticStageDocumentEnvelope = serde_json::from_slice(bytes)?;
        if envelope.kind != SEMANTIC_STAGE_DOCUMENT_KIND
            || envelope.format_version != SEMANTIC_STAGE_DOCUMENT_VERSION
        {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive semantic document",
                message: format!(
                    "expected kind {:?} version {}, got kind {:?} version {}",
                    SEMANTIC_STAGE_DOCUMENT_KIND,
                    SEMANTIC_STAGE_DOCUMENT_VERSION,
                    envelope.kind,
                    envelope.format_version
                ),
            }));
        }
        let document = envelope.archive;
        document.validate_detached_state()?;
        let rebuilt = document.encode()?;
        let reopened = Self::parse(&rebuilt)?;
        if reopened.encode()? != rebuilt {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive semantic document",
                message: "rebuilt archive is not stable after a fresh semantic import".to_string(),
            }));
        }
        Ok(document)
    }

    pub fn resource(&self, raw_path: &[u8]) -> Option<&StageResourceDocument> {
        self.resources
            .iter()
            .find(|resource| resource.raw_path == raw_path)
            .map(|resource| &resource.document)
    }

    pub fn resource_mut(&mut self, raw_path: &[u8]) -> Option<&mut StageResourceDocument> {
        self.resources
            .iter_mut()
            .find(|resource| resource.raw_path == raw_path)
            .map(|resource| &mut resource.document)
    }

    /// Rebuilds one semantic child resource without encoding the surrounding
    /// RARC/Yaz0 container. This is the detached-archive equivalent of reading
    /// an `archive.szs!/path` asset and never consults the imported source file.
    pub fn resource_bytes(&self, raw_path: &[u8]) -> Result<Option<Vec<u8>>> {
        let Some(resource) = self
            .resources
            .iter()
            .find(|resource| resource.raw_path == raw_path)
        else {
            return Ok(None);
        };
        encode_resource(&resource.document)
            .map(Some)
            .map_err(|source| SceneError::StageResource {
                path: display_raw_path(&resource.raw_path),
                source,
            })
    }

    /// Inserts a typed resource and any missing RARC directories as one
    /// transaction. Existing semantic resources are regenerated only in a
    /// temporary builder; the committed container remains payload-free.
    pub fn insert_resource(
        &mut self,
        raw_path: impl Into<Vec<u8>>,
        document: StageResourceDocument,
    ) -> Result<()> {
        let raw_path = normalize_resource_path(raw_path.into())?;
        if self.resource(&raw_path).is_some() {
            return Err(unsupported_stage_resource(format!(
                "resource {} already exists",
                display_raw_path(&raw_path)
            )));
        }
        validate_resource_path_kind(&raw_path, &document)?;
        let bytes = encode_resource(&document).map_err(|source| SceneError::StageResource {
            path: display_raw_path(&raw_path),
            source,
        })?;

        let mut builder = self.hydrated_builder()?;
        builder.insert_file(&raw_path, bytes)?;
        let mut archive = builder.into_document()?;
        detach_rarc_payloads(&mut archive);

        let mut resources = self.resources.clone();
        resources.push(StageResource { raw_path, document });
        self.archive = archive;
        self.resources = resources;
        Ok(())
    }

    /// Replaces an existing typed resource without changing its archive path.
    pub fn replace_resource(
        &mut self,
        raw_path: &[u8],
        document: StageResourceDocument,
    ) -> Result<StageResourceDocument> {
        let raw_path = normalize_resource_path(raw_path.to_vec())?;
        validate_resource_path_kind(&raw_path, &document)?;
        // Prove the replacement can be encoded before mutating the archive.
        encode_resource(&document).map_err(|source| SceneError::StageResource {
            path: display_raw_path(&raw_path),
            source,
        })?;
        let resource = self
            .resources
            .iter_mut()
            .find(|resource| resource.raw_path == raw_path)
            .ok_or_else(|| {
                unsupported_stage_resource(format!(
                    "resource {} was not found",
                    display_raw_path(&raw_path)
                ))
            })?;
        Ok(std::mem::replace(&mut resource.document, document))
    }

    /// Removes a typed resource and prunes newly empty archive directories.
    pub fn remove_resource(&mut self, raw_path: &[u8]) -> Result<StageResourceDocument> {
        let raw_path = normalize_resource_path(raw_path.to_vec())?;
        let resource_index = self
            .resources
            .iter()
            .position(|resource| resource.raw_path == raw_path)
            .ok_or_else(|| {
                unsupported_stage_resource(format!(
                    "resource {} was not found",
                    display_raw_path(&raw_path)
                ))
            })?;
        let mut builder = self.hydrated_builder()?;
        builder.remove_file(&raw_path)?;
        let mut archive = builder.into_document()?;
        detach_rarc_payloads(&mut archive);

        let mut resources = self.resources.clone();
        let removed = resources.remove(resource_index).document;
        self.archive = archive;
        self.resources = resources;
        Ok(removed)
    }

    fn hydrated_builder(&self) -> Result<RarcBuilder> {
        self.validate_detached_state()?;
        let mut archive = self.archive.clone();
        for resource in &self.resources {
            let bytes = encode_resource(&resource.document).map_err(|source| {
                SceneError::StageResource {
                    path: display_raw_path(&resource.raw_path),
                    source,
                }
            })?;
            archive.set_file_data(&resource.raw_path, bytes)?;
        }
        Ok(RarcBuilder::from_document(&archive)?)
    }

    /// Enumerates every transform-editable placement using semantic tree paths
    /// rather than offsets into the discarded import buffer.
    ///
    /// Most placements use the common `TActor` stream. A small set of
    /// decomp-verified authoring records (currently `AreaCylinder` and
    /// `Generator`) serialize the same three-vector editor transform as typed
    /// fields instead. Those records must participate in reconciliation too,
    /// otherwise a valid source-free address would appear to be missing.
    pub fn object_placements(&self) -> Vec<StageObjectPlacement> {
        let mut placements = Vec::new();
        for resource in &self.resources {
            if let StageResourceDocument::Placement(document) = &resource.document {
                collect_object_placements(
                    &resource.raw_path,
                    &document.root,
                    &mut Vec::new(),
                    &mut placements,
                );
            }
        }
        placements
    }

    /// Finds one semantic JDrama group by type and, for an `IdxGroup`, its
    /// typed `group_index` field. Type matching ignores namespace prefixes,
    /// and the returned path is a recursive child-index path with `[]`
    /// identifying the placement root. Ambiguous matches are rejected rather
    /// than silently selecting a stage-dependent sibling.
    pub fn find_group_record_path(
        &self,
        raw_resource_path: &[u8],
        type_name: &str,
        group_index: Option<u32>,
    ) -> Result<Option<Vec<usize>>> {
        let raw_resource_path = normalize_resource_path(raw_resource_path.to_vec())?;
        let document = match self.resource(&raw_resource_path) {
            Some(StageResourceDocument::Placement(document)) => document,
            Some(_) => {
                return Err(unsupported_stage_object(format!(
                    "{} is not a placement resource",
                    display_raw_path(&raw_resource_path)
                )));
            }
            None => {
                return Err(unsupported_stage_object(format!(
                    "placement resource {} was not found",
                    display_raw_path(&raw_resource_path)
                )));
            }
        };

        let mut matches = Vec::new();
        collect_group_record_paths(
            &document.root,
            type_name,
            group_index,
            &mut Vec::new(),
            &mut matches,
        );
        match matches.len() {
            0 => Ok(None),
            1 => Ok(matches.pop()),
            count => Err(unsupported_stage_object(format!(
                "group type '{}'{} is ambiguous in {} ({count} matches)",
                semantic_type_name(type_name),
                group_index
                    .map(|index| format!(" with group_index {index}"))
                    .unwrap_or_default(),
                display_raw_path(&raw_resource_path)
            ))),
        }
    }

    /// Finds one semantic JDrama group by its exact runtime name and type.
    ///
    /// Type matching ignores namespace prefixes, while the name comparison is
    /// deliberately exact because `TNameRef::searchF` verifies both the
    /// Shift-JIS key and the case-sensitive record name at runtime.
    pub fn find_named_group_record_path(
        &self,
        raw_resource_path: &[u8],
        type_name: &str,
        name: &str,
    ) -> Result<Option<Vec<usize>>> {
        let raw_resource_path = normalize_resource_path(raw_resource_path.to_vec())?;
        let document = match self.resource(&raw_resource_path) {
            Some(StageResourceDocument::Placement(document)) => document,
            Some(_) => {
                return Err(unsupported_stage_object(format!(
                    "{} is not a placement resource",
                    display_raw_path(&raw_resource_path)
                )));
            }
            None => {
                return Err(unsupported_stage_object(format!(
                    "placement resource {} was not found",
                    display_raw_path(&raw_resource_path)
                )));
            }
        };

        let mut matches = Vec::new();
        collect_named_group_record_paths(
            &document.root,
            type_name,
            name,
            &mut Vec::new(),
            &mut matches,
        );
        match matches.len() {
            0 => Ok(None),
            1 => Ok(matches.pop()),
            count => Err(unsupported_stage_object(format!(
                "group type '{}' named {name:?} is ambiguous in {} ({count} matches)",
                semantic_type_name(type_name),
                display_raw_path(&raw_resource_path)
            ))),
        }
    }

    /// Finds an indexed group only when it occupies one unique runtime slot
    /// directly beneath its owning group.
    ///
    /// `TStrategy::load` assigns each direct `IdxGroup` child into an array by
    /// `group_index`; a later child with the same index silently replaces the
    /// earlier pointer. Requiring both an exact name and a unique owner/index
    /// slot prevents authored records from targeting a group that the runtime
    /// never schedules.
    pub fn find_unique_owned_indexed_group_record_path(
        &self,
        raw_resource_path: &[u8],
        type_name: &str,
        name: &str,
        group_index: u32,
        owner_type_name: &str,
    ) -> Result<Option<Vec<usize>>> {
        let raw_resource_path = normalize_resource_path(raw_resource_path.to_vec())?;
        let document = match self.resource(&raw_resource_path) {
            Some(StageResourceDocument::Placement(document)) => document,
            Some(_) => {
                return Err(unsupported_stage_object(format!(
                    "{} is not a placement resource",
                    display_raw_path(&raw_resource_path)
                )));
            }
            None => {
                return Err(unsupported_stage_object(format!(
                    "placement resource {} was not found",
                    display_raw_path(&raw_resource_path)
                )));
            }
        };

        let mut named_matches = Vec::new();
        let mut slot_matches = Vec::new();
        let mut target_matches = Vec::new();
        collect_owned_indexed_group_record_paths(
            &document.root,
            None,
            type_name,
            name,
            group_index,
            owner_type_name,
            &mut Vec::new(),
            &mut named_matches,
            &mut slot_matches,
            &mut target_matches,
        );

        if named_matches.is_empty() {
            return Ok(None);
        }
        if named_matches.len() != 1 {
            return Err(unsupported_stage_object(format!(
                "group type '{}' named {name:?} is ambiguous in {} ({} matches)",
                semantic_type_name(type_name),
                display_raw_path(&raw_resource_path),
                named_matches.len()
            )));
        }
        if target_matches.is_empty() {
            return Err(unsupported_stage_object(format!(
                "group type '{}' named {name:?} in {} is not a direct child of '{}' with group_index {group_index}",
                semantic_type_name(type_name),
                display_raw_path(&raw_resource_path),
                semantic_type_name(owner_type_name)
            )));
        }
        if slot_matches.len() != 1 || target_matches.len() != 1 {
            return Err(unsupported_stage_object(format!(
                "'{}' has {} direct '{}' children with group_index {group_index} in {}; the runtime slot for {name:?} must be unique",
                semantic_type_name(owner_type_name),
                slot_matches.len(),
                semantic_type_name(type_name),
                display_raw_path(&raw_resource_path)
            )));
        }
        Ok(target_matches.pop())
    }

    pub fn set_object_transform(
        &mut self,
        raw_resource_path: &[u8],
        record_path: &[usize],
        transform: JDramaTransform,
    ) -> Result<()> {
        let document = self.placement_document_mut(raw_resource_path)?;
        let record = jdrama_record_mut(&mut document.root, record_path)?;
        set_editable_record_transform(record, transform).ok_or_else(|| {
            unsupported_stage_object(format!(
                "record {} in {} has no typed transform mapping",
                display_record_path(record_path),
                display_raw_path(raw_resource_path)
            ))
        })
    }

    /// Adds a fully typed actor or group under a semantic JDrama group.
    pub fn insert_placement_record(
        &mut self,
        raw_resource_path: &[u8],
        parent_path: &[usize],
        record: JDramaRecord,
    ) -> Result<Vec<usize>> {
        let document = self.placement_document_mut(raw_resource_path)?;
        let parent = jdrama_record_mut(&mut document.root, parent_path)?;
        let JDramaRecordPayload::Group { children, .. } = &mut parent.payload else {
            return Err(unsupported_stage_object(format!(
                "record {} in {} is not a group",
                display_record_path(parent_path),
                display_raw_path(raw_resource_path)
            )));
        };
        let mut path = parent_path.to_vec();
        path.push(children.len());
        children.push(record);
        Ok(path)
    }

    pub fn remove_placement_record(
        &mut self,
        raw_resource_path: &[u8],
        record_path: &[usize],
    ) -> Result<JDramaRecord> {
        let (&index, parent_path) = record_path.split_last().ok_or_else(|| {
            unsupported_stage_object("the root placement record cannot be removed")
        })?;
        let document = self.placement_document_mut(raw_resource_path)?;
        let parent = jdrama_record_mut(&mut document.root, parent_path)?;
        let JDramaRecordPayload::Group { children, .. } = &mut parent.payload else {
            return Err(unsupported_stage_object(format!(
                "record {} in {} is not a group",
                display_record_path(parent_path),
                display_raw_path(raw_resource_path)
            )));
        };
        if index >= children.len() {
            return Err(unsupported_stage_object(format!(
                "record path {} is outside {}",
                display_record_path(record_path),
                display_raw_path(raw_resource_path)
            )));
        }
        Ok(children.remove(index))
    }

    fn placement_document_mut(&mut self, raw_path: &[u8]) -> Result<&mut JDramaDocument> {
        match self.resource_mut(raw_path) {
            Some(StageResourceDocument::Placement(document)) => Ok(document),
            Some(_) => Err(unsupported_stage_object(format!(
                "{} is not a placement resource",
                display_raw_path(raw_path)
            ))),
            None => Err(unsupported_stage_object(format!(
                "placement resource {} was not found",
                display_raw_path(raw_path)
            ))),
        }
    }

    /// Rebuilds every child, the RARC data layout, and optional Yaz0 stream.
    pub fn encode(&self) -> Result<Vec<u8>> {
        self.validate_detached_state()?;
        let mut archive = self.archive.clone();
        for resource in &self.resources {
            if !document_matches_path(&resource.raw_path, &resource.document) {
                return Err(SceneError::StageResource {
                    path: display_raw_path(&resource.raw_path),
                    source: FormatError::Unsupported {
                        format: "source-free stage asset",
                        message: "semantic document kind does not match its archive path"
                            .to_string(),
                    },
                });
            }
            let bytes = encode_resource(&resource.document).map_err(|source| {
                SceneError::StageResource {
                    path: display_raw_path(&resource.raw_path),
                    source,
                }
            })?;
            archive.set_file_data(&resource.raw_path, bytes)?;
        }
        if let Some((index, _)) = archive
            .entries
            .iter()
            .enumerate()
            .find(|(_, entry)| !entry.is_directory() && entry.data.is_none())
        {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive",
                message: format!("file entry {index} has no semantic resource document"),
            }));
        }

        // Recalculate names, hashes, table offsets, payload offsets, partition
        // sizes, and file sizes. Imported offsets are accepted only as input
        // ordering hints; they are never copied into the rebuilt container.
        archive.canonicalize_layout()?;
        let rarc = archive.to_bytes()?;
        match self.compression {
            Some(StageCompression::Yaz0 { reserved }) => {
                Ok(sms_formats::encode_yaz0_with_reserved(&rarc, reserved)?)
            }
            None => Ok(rarc),
        }
    }

    fn validate_detached_state(&self) -> Result<()> {
        if self
            .archive
            .entries
            .iter()
            .any(|entry| entry.data.is_some())
        {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive semantic document",
                message: "RARC payload bytes are forbidden in a detached semantic document"
                    .to_string(),
            }));
        }

        let file_count = self
            .archive
            .entries
            .iter()
            .filter(|entry| !entry.is_directory())
            .count();
        if self.resources.len() != file_count {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive semantic document",
                message: format!(
                    "the RARC contains {file_count} files but the document has {} semantic resources",
                    self.resources.len()
                ),
            }));
        }

        let mut coverage = self.archive.clone();
        for resource in &self.resources {
            if !document_matches_path(&resource.raw_path, &resource.document) {
                return Err(SceneError::StageResource {
                    path: display_raw_path(&resource.raw_path),
                    source: FormatError::Unsupported {
                        format: "source-free stage asset",
                        message: "semantic document kind does not match its archive path"
                            .to_string(),
                    },
                });
            }
            coverage.set_file_data(&resource.raw_path, Vec::new())?;
        }
        if coverage
            .entries
            .iter()
            .any(|entry| !entry.is_directory() && entry.data.is_none())
        {
            return Err(SceneError::Format(FormatError::Unsupported {
                format: "stage archive semantic document",
                message: "at least one RARC file has no semantic resource document".to_string(),
            }));
        }
        Ok(())
    }
}

fn normalize_resource_path(mut raw_path: Vec<u8>) -> Result<Vec<u8>> {
    if raw_path.first() == Some(&b'/') {
        raw_path.remove(0);
    }
    if raw_path.is_empty()
        || raw_path.contains(&0)
        || raw_path
            .split(|byte| *byte == b'/')
            .any(|component| component.is_empty() || matches!(component, b"." | b".."))
    {
        return Err(unsupported_stage_resource(format!(
            "invalid or traversal-capable archive path {raw_path:02X?}"
        )));
    }
    Ok(raw_path)
}

fn validate_resource_path_kind(raw_path: &[u8], document: &StageResourceDocument) -> Result<()> {
    if document_matches_path(raw_path, document) {
        Ok(())
    } else {
        Err(SceneError::StageResource {
            path: display_raw_path(raw_path),
            source: FormatError::Unsupported {
                format: "source-free stage asset",
                message: "semantic document kind does not match its archive path".to_string(),
            },
        })
    }
}

fn detach_rarc_payloads(archive: &mut RarcDocument) {
    for entry in &mut archive.entries {
        if !entry.is_directory() {
            entry.take_file_data();
        }
    }
}

fn unsupported_stage_resource(message: impl Into<String>) -> SceneError {
    SceneError::Format(FormatError::Unsupported {
        format: "stage archive resource",
        message: message.into(),
    })
}

fn collect_object_placements(
    raw_resource_path: &[u8],
    record: &JDramaRecord,
    path: &mut Vec<usize>,
    placements: &mut Vec<StageObjectPlacement>,
) {
    if let Some(transform) = editable_record_transform(record) {
        placements.push(StageObjectPlacement {
            raw_resource_path: raw_resource_path.to_vec(),
            record_path: path.clone(),
            type_name: record.type_name.clone(),
            name: record.name.clone(),
            transform,
        });
    }
    if let JDramaRecordPayload::Group { children, .. } = &record.payload {
        for (index, child) in children.iter().enumerate() {
            path.push(index);
            collect_object_placements(raw_resource_path, child, path, placements);
            path.pop();
        }
    }
}

fn editable_record_transform(record: &JDramaRecord) -> Option<JDramaTransform> {
    match &record.payload {
        JDramaRecordPayload::Actor { transform, .. } => Some(*transform),
        JDramaRecordPayload::Fields { fields } => {
            let names = typed_field_transform_names(&record.type_name)?;
            Some(JDramaTransform {
                translation: vec3_field(fields, names.0)?,
                rotation: vec3_field(fields, names.1)?,
                scale: vec3_field(fields, names.2)?,
            })
        }
        _ => None,
    }
}

fn set_editable_record_transform(
    record: &mut JDramaRecord,
    transform: JDramaTransform,
) -> Option<()> {
    let typed_names = typed_field_transform_names(&record.type_name);
    match &mut record.payload {
        JDramaRecordPayload::Actor {
            transform: current, ..
        } => {
            *current = transform;
            Some(())
        }
        JDramaRecordPayload::Fields { fields } => {
            let names = typed_names?;
            set_vec3_field(fields, names.0, transform.translation)?;
            set_vec3_field(fields, names.1, transform.rotation)?;
            set_vec3_field(fields, names.2, transform.scale)?;
            Some(())
        }
        _ => None,
    }
}

fn typed_field_transform_names(
    type_name: &str,
) -> Option<(&'static str, &'static str, &'static str)> {
    match semantic_type_name(type_name) {
        "AreaCylinder" => Some(("center", "authoring_vector", "cylinder_parameters")),
        "Generator" => Some(("position", "rotation", "authoring_vector")),
        _ => None,
    }
}

fn vec3_field(fields: &[JDramaField], name: &str) -> Option<[f32; 3]> {
    fields.iter().find_map(|field| {
        (field.name == name)
            .then_some(&field.value)
            .and_then(|value| match value {
                JDramaFieldValue::Vec3F32(value) => Some(*value),
                _ => None,
            })
    })
}

fn set_vec3_field(fields: &mut [JDramaField], name: &str, value: [f32; 3]) -> Option<()> {
    let field = fields.iter_mut().find(|field| field.name == name)?;
    let JDramaFieldValue::Vec3F32(current) = &mut field.value else {
        return None;
    };
    *current = value;
    Some(())
}

fn collect_group_record_paths(
    record: &JDramaRecord,
    type_name: &str,
    group_index: Option<u32>,
    path: &mut Vec<usize>,
    matches: &mut Vec<Vec<usize>>,
) {
    let JDramaRecordPayload::Group { fields, children } = &record.payload else {
        return;
    };
    let type_matches = semantic_type_name(&record.type_name) == semantic_type_name(type_name);
    let index_matches = group_index.is_none_or(|expected| {
        semantic_type_name(&record.type_name) == "IdxGroup"
            && fields.iter().any(|field| {
                field.name == "group_index" && field.value == JDramaFieldValue::U32(expected)
            })
    });
    if type_matches && index_matches {
        matches.push(path.clone());
    }
    for (index, child) in children.iter().enumerate() {
        path.push(index);
        collect_group_record_paths(child, type_name, group_index, path, matches);
        path.pop();
    }
}

fn collect_named_group_record_paths(
    record: &JDramaRecord,
    type_name: &str,
    name: &str,
    path: &mut Vec<usize>,
    matches: &mut Vec<Vec<usize>>,
) {
    let JDramaRecordPayload::Group { children, .. } = &record.payload else {
        return;
    };
    if semantic_type_name(&record.type_name) == semantic_type_name(type_name) && record.name == name
    {
        matches.push(path.clone());
    }
    for (index, child) in children.iter().enumerate() {
        path.push(index);
        collect_named_group_record_paths(child, type_name, name, path, matches);
        path.pop();
    }
}

#[allow(clippy::too_many_arguments)]
fn collect_owned_indexed_group_record_paths(
    record: &JDramaRecord,
    parent_type_name: Option<&str>,
    type_name: &str,
    name: &str,
    group_index: u32,
    owner_type_name: &str,
    path: &mut Vec<usize>,
    named_matches: &mut Vec<Vec<usize>>,
    slot_matches: &mut Vec<Vec<usize>>,
    target_matches: &mut Vec<Vec<usize>>,
) {
    let JDramaRecordPayload::Group { fields, children } = &record.payload else {
        return;
    };
    let type_matches = semantic_type_name(&record.type_name) == semantic_type_name(type_name);
    let name_matches = type_matches && record.name == name;
    let index_matches = fields.iter().any(|field| {
        field.name == "group_index" && field.value == JDramaFieldValue::U32(group_index)
    });
    let owner_matches = parent_type_name
        .is_some_and(|parent| semantic_type_name(parent) == semantic_type_name(owner_type_name));
    if name_matches {
        named_matches.push(path.clone());
    }
    if type_matches && index_matches && owner_matches {
        slot_matches.push(path.clone());
        if name_matches {
            target_matches.push(path.clone());
        }
    }
    for (index, child) in children.iter().enumerate() {
        path.push(index);
        collect_owned_indexed_group_record_paths(
            child,
            Some(&record.type_name),
            type_name,
            name,
            group_index,
            owner_type_name,
            path,
            named_matches,
            slot_matches,
            target_matches,
        );
        path.pop();
    }
}

fn semantic_type_name(type_name: &str) -> &str {
    type_name.rsplit("::").next().unwrap_or(type_name)
}

fn jdrama_record_mut<'a>(
    mut record: &'a mut JDramaRecord,
    path: &[usize],
) -> Result<&'a mut JDramaRecord> {
    for (depth, index) in path.iter().copied().enumerate() {
        let JDramaRecordPayload::Group { children, .. } = &mut record.payload else {
            return Err(unsupported_stage_object(format!(
                "record path {} crosses a non-group at depth {depth}",
                display_record_path(path)
            )));
        };
        record = children.get_mut(index).ok_or_else(|| {
            unsupported_stage_object(format!(
                "record path {} has no child {index} at depth {depth}",
                display_record_path(path)
            ))
        })?;
    }
    Ok(record)
}

fn display_record_path(path: &[usize]) -> String {
    if path.is_empty() {
        return "root".to_string();
    }
    path.iter()
        .map(usize::to_string)
        .collect::<Vec<_>>()
        .join("/")
}

fn unsupported_stage_object(message: impl Into<String>) -> SceneError {
    SceneError::Format(FormatError::Unsupported {
        format: "stage object placement",
        message: message.into(),
    })
}

pub(crate) fn parse_resource(
    raw_path: &[u8],
    payload: &[u8],
) -> sms_formats::Result<StageResourceDocument> {
    let lower = raw_path
        .iter()
        .map(|byte| byte.to_ascii_lowercase())
        .collect::<Vec<_>>();
    if lower.ends_with(b".col") {
        return Ok(StageResourceDocument::Collision(ColFile::parse(payload)?));
    }
    if lower.ends_with(b".bas") {
        return Ok(StageResourceDocument::AnimationSound(BasFile::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".bmp") {
        return Ok(StageResourceDocument::Bitmap(BmpFile::parse(payload)?));
    }
    if lower.ends_with(b".bck")
        || lower.ends_with(b".btp")
        || lower.ends_with(b".btk")
        || lower.ends_with(b".bpk")
        || lower.ends_with(b".brk")
    {
        return Ok(StageResourceDocument::Animation(Box::new(
            J3dAnimationRebuildDocument::parse(payload)?,
        )));
    }
    if lower.ends_with(b".bmd") || lower.ends_with(b".bdl") || lower.ends_with(b".bmt") {
        return Ok(StageResourceDocument::Model(J3dRebuildDocument::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".bmg") {
        return Ok(StageResourceDocument::Message(BmgFile::parse(payload)?));
    }
    if lower.ends_with(b".jpa") {
        return Ok(StageResourceDocument::Particle(JpaxDocument::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".me") {
        return Ok(StageResourceDocument::Marker(MarkerTextFile::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".bti") {
        return Ok(StageResourceDocument::Texture(BtiFile::parse(payload)?));
    }
    if lower.ends_with(b".pad") {
        return Ok(StageResourceDocument::PlayerReplay(
            MarioRecordBundle::parse(payload)?,
        ));
    }
    if lower.ends_with(b".ral") {
        return Ok(StageResourceDocument::Rail(RalDocument::parse(payload)?));
    }
    if lower.ends_with(b".ymp") {
        return Ok(StageResourceDocument::PollutionMap(YmpDocument::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".sb") {
        return Ok(StageResourceDocument::Script(SpcDocument::parse(payload)?));
    }
    if lower.ends_with(b"linkdata.bin") {
        return Ok(StageResourceDocument::ReplayLinks(
            ReplayLinkDocument::parse(payload)?,
        ));
    }
    if lower.ends_with(b".bin") {
        return Ok(StageResourceDocument::Placement(JDramaDocument::parse(
            payload,
        )?));
    }
    if lower.ends_with(b".prm") {
        return Ok(StageResourceDocument::Parameters(PrmFile::parse(payload)?));
    }

    Err(FormatError::Unsupported {
        format: "source-free stage asset",
        message: format!(
            "no semantic importer/writer for archive path {}",
            display_raw_path(raw_path)
        ),
    })
}

fn encode_resource(document: &StageResourceDocument) -> sms_formats::Result<Vec<u8>> {
    match document {
        StageResourceDocument::Animation(document) => Ok(document.encode()?),
        StageResourceDocument::AnimationSound(document) => Ok(document.encode()?),
        StageResourceDocument::Bitmap(document) => Ok(document.encode()?),
        StageResourceDocument::Collision(document) => Ok(document.encode()?),
        StageResourceDocument::Message(document) => Ok(document.encode()?),
        StageResourceDocument::Marker(document) => Ok(document.encode()?),
        StageResourceDocument::Model(document) => Ok(document.to_bytes()?),
        StageResourceDocument::Particle(document) => Ok(document.to_bytes()?),
        StageResourceDocument::PlayerReplay(document) => Ok(document.encode()?),
        StageResourceDocument::Placement(document) => Ok(document.to_bytes()?),
        StageResourceDocument::PollutionMap(document) => Ok(document.encode()?),
        StageResourceDocument::Parameters(document) => Ok(document.encode()?),
        StageResourceDocument::Rail(document) => Ok(document.encode()?),
        StageResourceDocument::ReplayLinks(document) => Ok(document.encode()?),
        StageResourceDocument::Script(document) => Ok(document.encode()?),
        StageResourceDocument::Texture(document) => Ok(document.encode()?),
    }
}

fn document_matches_path(raw_path: &[u8], document: &StageResourceDocument) -> bool {
    let lower = raw_path
        .iter()
        .map(|byte| byte.to_ascii_lowercase())
        .collect::<Vec<_>>();
    match document {
        StageResourceDocument::Animation(document) => match &document.section {
            J3dAnimationSection::JointKey(_) => lower.ends_with(b".bck"),
            J3dAnimationSection::TexturePattern(_) => lower.ends_with(b".btp"),
            J3dAnimationSection::TextureSrt(_) => lower.ends_with(b".btk"),
            J3dAnimationSection::MaterialColor(_) => lower.ends_with(b".bpk"),
            J3dAnimationSection::TevRegister(_) => lower.ends_with(b".brk"),
        },
        StageResourceDocument::AnimationSound(_) => lower.ends_with(b".bas"),
        StageResourceDocument::Bitmap(_) => lower.ends_with(b".bmp"),
        StageResourceDocument::Collision(_) => lower.ends_with(b".col"),
        StageResourceDocument::Message(_) => lower.ends_with(b".bmg"),
        StageResourceDocument::Marker(_) => lower.ends_with(b".me"),
        StageResourceDocument::Model(document) => {
            (lower.ends_with(b".bmd") && document.file_type.starts_with(b"bmd"))
                || (lower.ends_with(b".bdl") && document.file_type.starts_with(b"bdl"))
                || (lower.ends_with(b".bmt") && document.file_type.starts_with(b"bmt"))
        }
        StageResourceDocument::Particle(_) => lower.ends_with(b".jpa"),
        StageResourceDocument::PlayerReplay(_) => lower.ends_with(b".pad"),
        StageResourceDocument::Placement(_) => {
            lower.ends_with(b".bin") && !lower.ends_with(b"linkdata.bin")
        }
        StageResourceDocument::PollutionMap(_) => lower.ends_with(b".ymp"),
        StageResourceDocument::Parameters(_) => lower.ends_with(b".prm"),
        StageResourceDocument::Rail(_) => lower.ends_with(b".ral"),
        StageResourceDocument::ReplayLinks(_) => lower.ends_with(b"linkdata.bin"),
        StageResourceDocument::Script(_) => lower.ends_with(b".sb"),
        StageResourceDocument::Texture(_) => lower.ends_with(b".bti"),
    }
}

fn display_raw_path(path: &[u8]) -> String {
    path.iter()
        .map(|byte| {
            if byte.is_ascii_graphic() || *byte == b' ' {
                char::from(*byte).to_string()
            } else {
                format!("%{byte:02X}")
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use sms_formats::{
        ColGroup, ColTriangle, ColVertex, J3dPaddingSpan, J3dRebuildDocument, J3dRebuildSection,
        J3dRebuildSectionData, J3dScalarArray, J3dVertexArray, J3dVertexArrayAttribute,
        J3dVertexAttributeFormat, J3dVertexSection, JDramaField, JDramaLightMap, JDramaRecord,
        JDramaRecordPayload, JDramaTransform, JpaxLayout, PrmEntry, PrmValue, RarcEntryRecord,
        RarcLayout, RarcNodeRecord,
    };

    use super::*;

    #[test]
    #[ignore = "diagnostic: requires SMS_BASE_ROOT"]
    fn report_retail_stage_resource_inventory() {
        let base_root = std::env::var_os("SMS_BASE_ROOT").expect("set SMS_BASE_ROOT");
        let archives = sms_formats::discover_scene_archives(base_root).unwrap();
        let mut counts = BTreeMap::<String, usize>::new();
        let mut samples = BTreeMap::<String, Vec<String>>::new();
        for archive in &archives {
            let source = std::fs::read(&archive.path).unwrap();
            let rarc = if source.starts_with(b"Yaz0") {
                sms_formats::decode_yaz0(&source).unwrap()
            } else {
                source
            };
            let index = RarcArchive::parse(rarc).unwrap();
            for entry in index.file_entries() {
                let name = entry.raw_path.rsplit(|byte| *byte == b'/').next().unwrap();
                let key = name
                    .iter()
                    .rposition(|byte| *byte == b'.')
                    .map(|index| String::from_utf8_lossy(&name[index..]).to_ascii_lowercase())
                    .unwrap_or_else(|| String::from_utf8_lossy(name).to_ascii_lowercase());
                *counts.entry(key.clone()).or_default() += 1;
                let sample_list = samples.entry(key).or_default();
                if sample_list.len() < 12 {
                    let payload = index.file_bytes(&entry.path).unwrap();
                    let header = payload
                        .iter()
                        .take(16)
                        .map(|byte| format!("{byte:02X}"))
                        .collect::<Vec<_>>()
                        .join("");
                    sample_list.push(format!(
                        "{}:{}:{}:{}",
                        archive.stage_id, entry.path, entry.size, header
                    ));
                }
            }
        }
        eprintln!(
            "retail stage resource inventory across {} archives: {counts:#?}",
            archives.len()
        );
        for key in [".bin", ".bmp", ".jpa", ".me", ".pad", ".ral", ".sb", ".ymp"] {
            eprintln!("{key} samples: {:#?}", samples.get(key));
        }
        assert_eq!(archives.len(), 107);
    }

    #[test]
    #[ignore = "requires SMS_BASE_ROOT with extracted retail stage archives"]
    fn source_free_rebuilds_every_retail_stage_archive() {
        let base_root = std::env::var_os("SMS_BASE_ROOT").expect("set SMS_BASE_ROOT");
        let archives = sms_formats::discover_scene_archives(base_root).unwrap();
        let mut rebuilt = 0usize;
        let mut failures = Vec::new();
        for archive in &archives {
            let mut source = std::fs::read(&archive.path).unwrap();
            let expected = source.clone();
            match SourceFreeStageArchive::parse(&source) {
                Ok(document) => {
                    source.fill(0xa5);
                    match document.encode() {
                        Ok(output) if output == expected => rebuilt += 1,
                        Ok(output) => failures.push(format!(
                            "{}: byte mismatch (source {}, rebuilt {})",
                            archive.path.display(),
                            expected.len(),
                            output.len()
                        )),
                        Err(error) => failures.push(format!("{}: {error}", archive.path.display())),
                    }
                }
                Err(error) => failures.push(format!("{}: {error}", archive.path.display())),
            }
        }
        let expected_count = if archives.iter().any(|archive| archive.stage_id == "test11") {
            108
        } else {
            107
        };
        assert_eq!(archives.len(), expected_count);
        assert!(
            failures.is_empty(),
            "{} stage rebuild failure(s), {rebuilt}/{expected_count} exact:\n{}",
            failures.len(),
            failures
                .into_iter()
                .take(107)
                .collect::<Vec<_>>()
                .join("\n")
        );
        eprintln!("source-free stage archive census rebuilt {rebuilt}/{expected_count} exactly");
    }

    #[test]
    fn source_free_core_archive_rebuilds_byte_identically() {
        let mut source = fixture_archive(false);
        let expected = source.clone();
        let document = SourceFreeStageArchive::parse(&source).expect("strict source-free import");
        source.fill(0xA5);
        let rebuilt = document.encode().expect("strict source-free export");
        assert_eq!(rebuilt, expected);
    }

    #[test]
    fn source_free_core_archive_rebuilds_yaz0_byte_identically() {
        let mut source = fixture_archive(true);
        let expected = source.clone();
        let document = SourceFreeStageArchive::parse(&source).expect("strict source-free import");
        source.fill(0xA5);
        let rebuilt = document.encode().expect("strict source-free export");
        assert_eq!(rebuilt, expected);
    }

    #[test]
    fn detached_semantic_json_rebuilds_without_the_source_archive() {
        let mut source = fixture_archive(true);
        let expected = source.clone();
        let document = SourceFreeStageArchive::parse(&source).unwrap();
        let semantic_json = document.to_semantic_json().unwrap();
        source.fill(0xA5);

        let reopened = SourceFreeStageArchive::from_semantic_json(&semantic_json).unwrap();
        assert_eq!(reopened.encode().unwrap(), expected);
    }

    #[test]
    fn detached_semantic_document_rejects_cached_rarc_payloads() {
        let source = fixture_archive(false);
        let mut document = SourceFreeStageArchive::parse(&source).unwrap();
        let entry = document
            .archive
            .entries
            .iter_mut()
            .find(|entry| !entry.is_directory())
            .unwrap();
        entry.data = Some(vec![0xde, 0xad, 0xbe, 0xef]);

        let error = document.encode().unwrap_err().to_string();
        assert!(error.contains("payload bytes are forbidden"), "{error}");
        assert!(document.to_semantic_json().is_err());
    }

    #[test]
    fn detached_semantic_document_rejects_unknown_versions() {
        let source = fixture_archive(false);
        let document = SourceFreeStageArchive::parse(&source).unwrap();
        let mut json: serde_json::Value =
            serde_json::from_slice(&document.to_semantic_json().unwrap()).unwrap();
        json["format_version"] = serde_json::json!(SEMANTIC_STAGE_DOCUMENT_VERSION + 1);

        let error = SourceFreeStageArchive::from_semantic_json(&serde_json::to_vec(&json).unwrap())
            .unwrap_err()
            .to_string();
        assert!(error.contains("expected kind"), "{error}");
    }

    #[test]
    fn new_source_free_archive_has_a_detached_scene_root() {
        let archive = SourceFreeStageArchive::new().unwrap();
        assert_eq!(
            archive.origin(),
            &StageOrigin::Blank {
                target_slot: "test11".to_string(),
                preset_version: 1,
            }
        );
        assert!(archive.resources().is_empty());
        assert_eq!(archive.archive.nodes.len(), 1);
        assert_eq!(archive.archive.nodes[0].raw_name, b"scene");
        assert!(archive
            .archive
            .entries
            .iter()
            .all(|entry| entry.data.is_none()));

        let encoded = archive.encode().unwrap();
        let reopened = SourceFreeStageArchive::parse(&encoded).unwrap();
        assert_eq!(reopened.origin(), &StageOrigin::ImportedArchive);
        assert!(reopened.resources().is_empty());
        assert_eq!(reopened.encode().unwrap(), encoded);
    }

    #[test]
    fn typed_resource_insert_replace_and_remove_are_transactional() {
        let source = fixture_archive(false);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        let authored = StageResourceDocument::Parameters(PrmFile {
            entries: vec![PrmEntry {
                name: "mSize".to_string(),
                value: PrmValue::from_f32(1.0),
            }],
        });
        archive
            .insert_resource(b"mapobj/authored.prm".to_vec(), authored.clone())
            .unwrap();
        assert_eq!(archive.resource(b"mapobj/authored.prm"), Some(&authored));
        assert!(archive
            .archive
            .entries
            .iter()
            .all(|entry| entry.data.is_none()));

        let replacement = StageResourceDocument::Parameters(PrmFile {
            entries: vec![PrmEntry {
                name: "mSize".to_string(),
                value: PrmValue::from_f32(2.0),
            }],
        });
        assert_eq!(
            archive
                .replace_resource(b"mapobj/authored.prm", replacement.clone())
                .unwrap(),
            authored
        );
        let removed = archive.remove_resource(b"effect.jpa").unwrap();
        assert!(matches!(removed, StageResourceDocument::Particle(_)));

        let encoded = archive.encode().unwrap();
        let reopened = SourceFreeStageArchive::parse(&encoded).unwrap();
        assert_eq!(
            reopened.resource(b"mapobj/authored.prm"),
            Some(&replacement)
        );
        assert!(reopened.resource(b"effect.jpa").is_none());
        assert_eq!(reopened.encode().unwrap(), encoded);
    }

    #[test]
    fn resource_mutation_rejects_conflicts_kind_mismatches_and_traversal() {
        let source = fixture_archive(false);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        let parameter = StageResourceDocument::Parameters(PrmFile {
            entries: Vec::new(),
        });
        assert!(archive
            .insert_resource(b"map.col".to_vec(), parameter.clone())
            .is_err());
        assert!(archive
            .insert_resource(b"../authored.prm".to_vec(), parameter.clone())
            .is_err());
        assert!(archive
            .insert_resource(b"authored.col".to_vec(), parameter)
            .is_err());
        assert_eq!(archive.encode().unwrap(), source);
    }

    #[test]
    fn geometry_collision_and_placement_edits_survive_a_fresh_reimport() {
        let source = fixture_archive(true);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        for resource in archive.resources_mut() {
            match &mut resource.document {
                StageResourceDocument::Animation(_) => {}
                StageResourceDocument::Collision(collision) => {
                    collision.vertices_mut()[0].position[1] = 25.0;
                }
                StageResourceDocument::AnimationSound(_) => {}
                StageResourceDocument::Bitmap(_) => {}
                StageResourceDocument::Model(model) => {
                    let positions = model
                        .sections
                        .iter_mut()
                        .find_map(|section| match &mut section.data {
                            J3dRebuildSectionData::Vertices(vertices) => vertices
                                .arrays
                                .iter_mut()
                                .find(|array| array.attribute == J3dVertexArrayAttribute::Position)
                                .map(|array| &mut array.values),
                            _ => None,
                        })
                        .expect("fixture model has positions");
                    let J3dScalarArray::Float32Bits(values) = positions else {
                        panic!("fixture positions are f32");
                    };
                    values[1] = 25.0f32.to_bits();
                }
                StageResourceDocument::Particle(_) => {}
                StageResourceDocument::PlayerReplay(_) => {}
                StageResourceDocument::Message(_) => {}
                StageResourceDocument::Marker(_) => {}
                StageResourceDocument::Placement(placement) => {
                    let JDramaRecordPayload::Group { children, .. } = &mut placement.root.payload
                    else {
                        panic!("fixture root is a group");
                    };
                    let JDramaRecordPayload::Actor { transform, .. } = &mut children[0].payload
                    else {
                        panic!("fixture child is an actor");
                    };
                    transform.translation[0] = 123.0;
                }
                StageResourceDocument::PollutionMap(_) => {}
                StageResourceDocument::Parameters(_) => {}
                StageResourceDocument::Rail(_) => {}
                StageResourceDocument::ReplayLinks(_) => {}
                StageResourceDocument::Script(_) => {}
                StageResourceDocument::Texture(_) => {}
            }
        }

        let edited = archive.encode().unwrap();
        assert_ne!(edited, source);
        let reopened = SourceFreeStageArchive::parse(&edited).unwrap();
        let collision = match reopened.resource(b"map.col") {
            Some(StageResourceDocument::Collision(collision)) => collision,
            _ => panic!("reopened collision is missing"),
        };
        assert_eq!(collision.vertices()[0].position[1], 25.0);
        let model = match reopened.resource(b"map.bmd") {
            Some(StageResourceDocument::Model(model)) => model,
            _ => panic!("reopened model is missing"),
        };
        let positions = model
            .sections
            .iter()
            .find_map(|section| match &section.data {
                J3dRebuildSectionData::Vertices(vertices) => vertices
                    .arrays
                    .iter()
                    .find(|array| array.attribute == J3dVertexArrayAttribute::Position)
                    .map(|array| &array.values),
                _ => None,
            })
            .expect("reopened model has positions");
        let J3dScalarArray::Float32Bits(values) = positions else {
            panic!("reopened fixture positions are f32");
        };
        assert_eq!(f32::from_bits(values[1]), 25.0);
        let placement = match reopened.resource(b"scene.bin") {
            Some(StageResourceDocument::Placement(placement)) => placement,
            _ => panic!("reopened placement is missing"),
        };
        let JDramaRecordPayload::Group { children, .. } = &placement.root.payload else {
            panic!("reopened root is a group");
        };
        let JDramaRecordPayload::Actor { transform, .. } = &children[0].payload else {
            panic!("reopened child is an actor");
        };
        assert_eq!(transform.translation[0], 123.0);
    }

    #[test]
    fn semantic_object_paths_support_add_edit_and_remove() {
        let source = fixture_archive(true);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        let original = archive.object_placements();
        assert_eq!(original.len(), 1);
        let mut moved = original[0].transform;
        moved.translation = [40.0, 50.0, 60.0];
        archive
            .set_object_transform(b"scene.bin", &original[0].record_path, moved)
            .unwrap();

        let inserted = JDramaRecord::new(
            "MapStaticObj",
            "inserted",
            JDramaRecordPayload::Actor {
                transform: JDramaTransform {
                    translation: [7.0, 8.0, 9.0],
                    rotation: [0.0, 0.0, 0.0],
                    scale: [1.0, 1.0, 1.0],
                },
                character_name: "inserted".to_string(),
                light_map: JDramaLightMap::default(),
                fields: Vec::new(),
            },
        )
        .unwrap();
        let inserted_path = archive
            .insert_placement_record(b"scene.bin", &[], inserted)
            .unwrap();

        let rebuilt = archive.encode().unwrap();
        let mut reopened = SourceFreeStageArchive::parse(&rebuilt).unwrap();
        let placements = reopened.object_placements();
        assert_eq!(placements.len(), 2);
        assert_eq!(placements[0].transform.translation, [40.0, 50.0, 60.0]);
        assert_eq!(placements[1].name, "inserted");
        assert_eq!(placements[1].transform.translation, [7.0, 8.0, 9.0]);

        let removed = reopened
            .remove_placement_record(b"scene.bin", &inserted_path)
            .unwrap();
        assert_eq!(removed.name, "inserted");
        let reopened_again = SourceFreeStageArchive::parse(&reopened.encode().unwrap()).unwrap();
        assert_eq!(reopened_again.object_placements().len(), 1);
    }

    #[test]
    fn semantic_group_lookup_is_recursive_namespaced_and_index_aware() {
        let source = fixture_archive(false);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        let indexed = JDramaRecord::new(
            "JDrama::IdxGroup",
            "indexed",
            JDramaRecordPayload::Group {
                fields: vec![JDramaField {
                    name: "group_index".to_string(),
                    value: JDramaFieldValue::U32(7),
                }],
                children: Vec::new(),
            },
        )
        .unwrap();
        let nested = JDramaRecord::new(
            "JDrama::GroupObj",
            "nested",
            JDramaRecordPayload::Group {
                fields: Vec::new(),
                children: vec![indexed],
            },
        )
        .unwrap();
        let root = JDramaRecord::new(
            "JDrama::Strategy",
            "root",
            JDramaRecordPayload::Group {
                fields: Vec::new(),
                children: vec![nested],
            },
        )
        .unwrap();
        archive
            .replace_resource(
                b"scene.bin",
                StageResourceDocument::Placement(JDramaDocument { root }),
            )
            .unwrap();

        assert_eq!(
            archive
                .find_group_record_path(b"scene.bin", "Strategy", None)
                .unwrap(),
            Some(Vec::new())
        );
        assert_eq!(
            archive
                .find_group_record_path(b"scene.bin", "JDrama::IdxGroup", Some(7))
                .unwrap(),
            Some(vec![0, 0])
        );
        assert_eq!(
            archive
                .find_named_group_record_path(b"scene.bin", "IdxGroup", "indexed")
                .unwrap(),
            Some(vec![0, 0])
        );
        assert_eq!(
            archive
                .find_named_group_record_path(b"scene.bin", "IdxGroup", "missing")
                .unwrap(),
            None
        );
        assert_eq!(
            archive
                .find_group_record_path(b"scene.bin", "IdxGroup", Some(8))
                .unwrap(),
            None
        );

        let rebuilt = archive.encode().unwrap();
        let mut reopened = SourceFreeStageArchive::parse(&rebuilt).unwrap();
        assert_eq!(
            reopened
                .find_group_record_path(b"scene.bin", "IdxGroup", Some(7))
                .unwrap(),
            Some(vec![0, 0])
        );
        assert_eq!(
            reopened
                .find_named_group_record_path(b"scene.bin", "JDrama::IdxGroup", "indexed")
                .unwrap(),
            Some(vec![0, 0])
        );
        let document = match reopened.resource_mut(b"scene.bin").unwrap() {
            StageResourceDocument::Placement(document) => document,
            _ => panic!("scene.bin has the wrong semantic kind"),
        };
        let JDramaRecordPayload::Group { children, .. } = &mut document.root.payload else {
            panic!("fixture root is not a group");
        };
        children.push(
            JDramaRecord::new(
                "Strategy",
                "ambiguous",
                JDramaRecordPayload::Group {
                    fields: Vec::new(),
                    children: Vec::new(),
                },
            )
            .unwrap(),
        );
        let error = reopened
            .find_group_record_path(b"scene.bin", "JDrama::Strategy", None)
            .unwrap_err()
            .to_string();
        assert!(error.contains("ambiguous"), "{error}");

        let document = match reopened.resource_mut(b"scene.bin").unwrap() {
            StageResourceDocument::Placement(document) => document,
            _ => panic!("scene.bin has the wrong semantic kind"),
        };
        let JDramaRecordPayload::Group { children, .. } = &mut document.root.payload else {
            panic!("fixture root is not a group");
        };
        children.push(
            JDramaRecord::new(
                "IdxGroup",
                "indexed",
                JDramaRecordPayload::Group {
                    fields: vec![JDramaField {
                        name: "group_index".to_string(),
                        value: JDramaFieldValue::U32(9),
                    }],
                    children: Vec::new(),
                },
            )
            .unwrap(),
        );
        let error = reopened
            .find_named_group_record_path(b"scene.bin", "IdxGroup", "indexed")
            .unwrap_err()
            .to_string();
        assert!(error.contains("named \"indexed\""), "{error}");
        assert!(error.contains("ambiguous"), "{error}");
    }

    #[test]
    fn owned_indexed_group_lookup_requires_the_unique_runtime_slot() {
        let source = fixture_archive(false);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        let indexed_group = |name: &str, index: u32| {
            JDramaRecord::new(
                "JDrama::IdxGroup",
                name,
                JDramaRecordPayload::Group {
                    fields: vec![JDramaField {
                        name: "group_index".to_string(),
                        value: JDramaFieldValue::U32(index),
                    }],
                    children: Vec::new(),
                },
            )
            .unwrap()
        };
        let replace_strategy = |archive: &mut SourceFreeStageArchive,
                                children: Vec<JDramaRecord>| {
            let root = JDramaRecord::new(
                "JDrama::Strategy",
                "strategy",
                JDramaRecordPayload::Group {
                    fields: Vec::new(),
                    children,
                },
            )
            .unwrap();
            archive
                .replace_resource(
                    b"scene.bin",
                    StageResourceDocument::Placement(JDramaDocument { root }),
                )
                .unwrap();
        };

        replace_strategy(&mut archive, vec![indexed_group("マップグループ", 0)]);
        assert_eq!(
            archive
                .find_unique_owned_indexed_group_record_path(
                    b"scene.bin",
                    "IdxGroup",
                    "マップグループ",
                    0,
                    "Strategy",
                )
                .unwrap(),
            Some(vec![0])
        );

        replace_strategy(&mut archive, vec![indexed_group("マップグループ", 1)]);
        let wrong_index = archive
            .find_unique_owned_indexed_group_record_path(
                b"scene.bin",
                "IdxGroup",
                "マップグループ",
                0,
                "Strategy",
            )
            .unwrap_err()
            .to_string();
        assert!(wrong_index.contains("group_index 0"), "{wrong_index}");

        let outside = JDramaRecord::new(
            "GroupObj",
            "root",
            JDramaRecordPayload::Group {
                fields: Vec::new(),
                children: vec![
                    indexed_group("マップグループ", 0),
                    JDramaRecord::new(
                        "Strategy",
                        "strategy",
                        JDramaRecordPayload::Group {
                            fields: Vec::new(),
                            children: Vec::new(),
                        },
                    )
                    .unwrap(),
                ],
            },
        )
        .unwrap();
        archive
            .replace_resource(
                b"scene.bin",
                StageResourceDocument::Placement(JDramaDocument { root: outside }),
            )
            .unwrap();
        let outside_strategy = archive
            .find_unique_owned_indexed_group_record_path(
                b"scene.bin",
                "IdxGroup",
                "マップグループ",
                0,
                "Strategy",
            )
            .unwrap_err()
            .to_string();
        assert!(
            outside_strategy.contains("direct child"),
            "{outside_strategy}"
        );

        replace_strategy(
            &mut archive,
            vec![
                indexed_group("マップグループ", 0),
                indexed_group("duplicate runtime slot", 0),
            ],
        );
        let duplicate_slot = archive
            .find_unique_owned_indexed_group_record_path(
                b"scene.bin",
                "IdxGroup",
                "マップグループ",
                0,
                "Strategy",
            )
            .unwrap_err()
            .to_string();
        assert!(
            duplicate_slot.contains("must be unique"),
            "{duplicate_slot}"
        );
    }

    #[test]
    fn unsupported_children_are_rejected_instead_of_cached() {
        let mut document = fixture_rarc();
        document.nodes[0].entry_count += 1;
        document.entries.push(RarcEntryRecord {
            file_id: 3,
            name_hash: 0,
            flags: 0x11,
            name_offset: 0,
            raw_name: b"opaque.dat".to_vec(),
            data_offset: 0,
            size: 3,
            reserved: 0,
            data: Some(vec![1, 2, 3]),
        });
        document.canonicalize_layout().unwrap();
        let source = document.to_bytes().unwrap();
        let error = SourceFreeStageArchive::parse(&source).unwrap_err();
        assert!(error.to_string().contains("opaque.dat"));
    }

    #[test]
    fn resource_document_kind_must_match_its_archive_path() {
        let source = fixture_archive(false);
        let mut archive = SourceFreeStageArchive::parse(&source).unwrap();
        *archive.resource_mut(b"map.col").unwrap() = StageResourceDocument::Parameters(PrmFile {
            entries: vec![PrmEntry {
                name: "mSize".to_string(),
                value: PrmValue::from_f32(1.0),
            }],
        });
        let error = archive.encode().unwrap_err().to_string();
        assert!(error.contains("map.col"), "{error}");
        assert!(error.contains("does not match"), "{error}");
    }

    #[test]
    fn j3d_resource_subtype_must_match_its_exact_extension() {
        let animation = StageResourceDocument::Animation(Box::new(J3dAnimationRebuildDocument {
            header_tag: sms_formats::J3dAnimationHeaderTag::AllFf,
            layout: sms_formats::J3dAnimationLayout {
                actual_section_size: 0,
                declared_section_size: 0,
                padding: Vec::new(),
            },
            section: J3dAnimationSection::TexturePattern(
                sms_formats::J3dTexturePatternAnimationSection {
                    attribute: 0,
                    header_padding: 0,
                    max_frame: 0,
                    tables: Vec::new(),
                    texture_indices: Vec::new(),
                    material_remap: Vec::new(),
                    material_names: sms_formats::J3dAnimationNameTable {
                        entries: Vec::new(),
                    },
                    offsets: [0; 4],
                },
            ),
        }));
        assert!(document_matches_path(b"anim.btp", &animation));
        assert!(!document_matches_path(b"anim.btk", &animation));

        let bmt = StageResourceDocument::Model(J3dRebuildDocument {
            file_type: *b"bmt3",
            version_tag: *b"SVR3",
            reserved_words: [u32::MAX; 3],
            declared_section_count: 0,
            sections: Vec::new(),
        });
        assert!(document_matches_path(b"material.bmt", &bmt));
        assert!(!document_matches_path(b"material.bmd", &bmt));
    }

    fn fixture_archive(yaz0: bool) -> Vec<u8> {
        let mut document = fixture_rarc();
        document.canonicalize_layout().unwrap();
        let rarc = document.to_bytes().unwrap();
        if yaz0 {
            sms_formats::encode_yaz0(&rarc).unwrap()
        } else {
            rarc
        }
    }

    fn fixture_rarc() -> RarcDocument {
        let placement = JDramaDocument {
            root: JDramaRecord::new(
                "NameRefGrp",
                "root",
                JDramaRecordPayload::Group {
                    fields: Vec::new(),
                    children: vec![JDramaRecord::new(
                        "MapStaticObj",
                        "fixture",
                        JDramaRecordPayload::Actor {
                            transform: JDramaTransform {
                                translation: [1.0, 2.0, 3.0],
                                rotation: [0.0, 90.0, 0.0],
                                scale: [1.0, 1.0, 1.0],
                            },
                            character_name: "fixture".to_string(),
                            light_map: JDramaLightMap::default(),
                            fields: Vec::new(),
                        },
                    )
                    .unwrap()],
                },
            )
            .unwrap(),
        }
        .to_bytes()
        .unwrap();
        let collision = ColFile::new(
            vec![
                ColVertex::new(0.0, 0.0, 0.0),
                ColVertex::new(1.0, 0.0, 0.0),
                ColVertex::new(0.0, 0.0, 1.0),
            ],
            vec![ColGroup {
                surface_type: 0,
                has_per_triangle_data: false,
                triangles: vec![ColTriangle {
                    vertex_indices: [0, 1, 2],
                    attribute_0: 0,
                    attribute_1: 0,
                    data: None,
                }],
            }],
        )
        .encode()
        .unwrap();
        let parameter = PrmFile {
            entries: vec![PrmEntry {
                name: "mSize".to_string(),
                value: PrmValue::from_f32(9.8),
            }],
        }
        .encode()
        .unwrap();
        let model = fixture_model().to_bytes().unwrap();
        let particle = JpaxDocument {
            blocks: Vec::new(),
            layout: JpaxLayout::Standard,
            trailing_zero_padding: 0,
        }
        .to_bytes()
        .unwrap();

        let resources = [
            (b"scene.bin".as_slice(), placement),
            (b"map.col".as_slice(), collision),
            (b"map.bmd".as_slice(), model),
            (b"effect.jpa".as_slice(), particle),
            (b"params.prm".as_slice(), parameter),
        ];
        let mut entries = resources
            .into_iter()
            .enumerate()
            .map(|(index, (name, data))| RarcEntryRecord {
                file_id: index as u16,
                name_hash: 0,
                flags: 0x11,
                name_offset: 0,
                raw_name: name.to_vec(),
                data_offset: 0,
                size: data.len() as u32,
                reserved: 0,
                data: Some(data),
            })
            .collect::<Vec<_>>();
        entries.extend(root_directory_entries());
        RarcDocument {
            layout: RarcLayout {
                file_size: 0,
                header_size: 0x20,
                data_offset: 0,
                data_size: 0,
                mram_data_size: 0,
                aram_data_size: 0,
                dvd_data_size: 0,
                metadata_present: true,
                node_offset: 0,
                entry_offset: 0,
                string_table_offset: 0,
                string_table_size: 0,
                next_free_file_id: entries.len() as u16,
                sync_file_ids: 1,
                info_reserved: [0; 5],
                alignment: 0x20,
                padding_byte: 0,
            },
            nodes: vec![RarcNodeRecord {
                node_type: *b"ROOT",
                name_offset: 0,
                name_hash: 0,
                raw_name: b"root".to_vec(),
                entry_count: entries.len() as u16,
                first_entry_index: 0,
            }],
            entries,
        }
    }

    fn root_directory_entries() -> [RarcEntryRecord; 2] {
        [
            RarcEntryRecord {
                file_id: u16::MAX,
                name_hash: 0,
                flags: 0x02,
                name_offset: 0,
                raw_name: b".".to_vec(),
                data_offset: 0,
                size: 0,
                reserved: 0,
                data: None,
            },
            RarcEntryRecord {
                file_id: u16::MAX,
                name_hash: 0,
                flags: 0x02,
                name_offset: 0,
                raw_name: b"..".to_vec(),
                data_offset: u32::MAX,
                size: 0,
                reserved: 0,
                data: None,
            },
        ]
    }

    fn fixture_model() -> J3dRebuildDocument {
        let mut offsets = [0; 14];
        offsets[0] = 0x40;
        offsets[1] = 0x60;
        J3dRebuildDocument {
            file_type: *b"bmd3",
            version_tag: *b"SVR3",
            reserved_words: [u32::MAX; 3],
            declared_section_count: 1,
            sections: vec![J3dRebuildSection {
                declared_size: 0xa0,
                data: J3dRebuildSectionData::Vertices(J3dVertexSection {
                    offsets,
                    formats: vec![
                        J3dVertexAttributeFormat {
                            attribute: 9,
                            component_count: 1,
                            component_type: 4,
                            fractional_bits: 0,
                            reserved: [0; 3],
                        },
                        J3dVertexAttributeFormat {
                            attribute: 0xff,
                            component_count: 0,
                            component_type: 0,
                            fractional_bits: 0,
                            reserved: [0; 3],
                        },
                    ],
                    arrays: vec![J3dVertexArray {
                        attribute: J3dVertexArrayAttribute::Position,
                        offset: 0x60,
                        values: J3dScalarArray::Float32Bits(
                            [0.0f32, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
                                .map(f32::to_bits)
                                .to_vec(),
                        ),
                    }],
                }),
                padding: Vec::<J3dPaddingSpan>::new(),
            }],
        }
    }
}
