use std::collections::{BTreeMap, BTreeSet};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::{json, Value};

const FIXTURE_ROOT: &str = "crates/sms-authoring/tests/fixtures/gltf";

pub(super) fn run(repo_root: &Path, arguments: &[OsString]) -> Result<(), String> {
    let check = match arguments {
        [] => false,
        [argument] if argument == OsStr::new("--check") => true,
        [argument] if argument == OsStr::new("--help") || argument == OsStr::new("-h") => {
            return Err("usage: cargo gltf-fixtures [--check]".to_string());
        }
        _ => return Err("usage: cargo gltf-fixtures [--check]".to_string()),
    };

    let root = repo_root.join(FIXTURE_ROOT);
    let expected = fixture_files()?;
    if check {
        check_files(&root, &expected)?;
        println!("glTF fixtures are current ({} files).", expected.len());
    } else {
        write_files(&root, &expected)?;
        println!(
            "Generated {} glTF fixture files in {}.",
            expected.len(),
            root.display()
        );
    }
    Ok(())
}

pub(super) fn check(repo_root: &Path) -> Result<(), String> {
    check_files(&repo_root.join(FIXTURE_ROOT), &fixture_files()?)
}

fn fixture_files() -> Result<BTreeMap<PathBuf, Vec<u8>>, String> {
    let mut files = BTreeMap::new();
    files.insert(
        PathBuf::from("README.md"),
        br#"# Project-authored glTF fixtures

Every asset in this directory is generated by `cargo gltf-fixtures`. The
geometry, images, names, and binary payloads were authored specifically for
the Graffito-Editor tests. They contain no Nintendo or third-party content
and inherit the repository's MIT license.

Run `cargo gltf-fixtures --check` to verify byte-for-byte freshness. Valid,
unsupported, rejected, security, and intentionally invalid inputs live in
separate folders so conformance expectations remain explicit.
"#
        .to_vec(),
    );

    add_minimal_external(&mut files)?;
    add_hierarchy_multiprimitive(&mut files)?;
    add_primitive_modes(&mut files)?;
    add_accessor_layouts(&mut files)?;
    add_material_textures(&mut files)?;
    add_embedded_texture(&mut files)?;
    add_collision_fixtures(&mut files)?;
    add_pbr_diagnostics(&mut files)?;
    add_name_fixtures(&mut files)?;
    add_unsupported_fixtures(&mut files)?;
    add_security_fixtures(&mut files)?;
    add_invalid_fixtures(&mut files)?;
    Ok(files)
}

fn add_minimal_external(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for value in [-0.5_f32, 0.0, -0.5, 0.5, 0.0, -0.5, 0.0, 0.0, 0.5] {
        push_f32(&mut bin, value);
    }
    for _ in 0..3 {
        for value in [0.0_f32, 1.0, 0.0] {
            push_f32(&mut bin, value);
        }
    }
    for _ in 0..3 {
        for value in [1.0_f32, 0.0, 0.0, 1.0] {
            push_f32(&mut bin, value);
        }
    }
    for value in [0.0_f32, 0.0, 1.0, 0.0, 0.5, 1.0] {
        push_f32(&mut bin, value);
    }
    bin.extend_from_slice(&[255, 0, 0, 255, 0, 255, 0, 255, 0, 0, 255, 255]);
    for index in [0_u16, 2, 1] {
        push_u16(&mut bin, index);
    }

    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "GroundTriangle", "mesh": 0}],
        "meshes": [{"name": "Ground", "primitives": [{
            "attributes": {"POSITION": 0, "NORMAL": 1, "TANGENT": 2, "TEXCOORD_0": 3, "COLOR_0": 4},
            "indices": 5,
            "mode": 4
        }]}],
        "buffers": [{"uri": "mesh.bin", "byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36, "target": 34962},
            {"buffer": 0, "byteOffset": 36, "byteLength": 36, "target": 34962},
            {"buffer": 0, "byteOffset": 72, "byteLength": 48, "target": 34962},
            {"buffer": 0, "byteOffset": 120, "byteLength": 24, "target": 34962},
            {"buffer": 0, "byteOffset": 144, "byteLength": 12, "target": 34962},
            {"buffer": 0, "byteOffset": 156, "byteLength": 6, "target": 34963}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-0.5, 0.0, -0.5], "max": [0.5, 0.0, 0.5]},
            {"bufferView": 1, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 2, "componentType": 5126, "count": 3, "type": "VEC4"},
            {"bufferView": 3, "componentType": 5126, "count": 3, "type": "VEC2"},
            {"bufferView": 4, "componentType": 5121, "normalized": true, "count": 3, "type": "VEC4"},
            {"bufferView": 5, "componentType": 5123, "count": 3, "type": "SCALAR", "min": [0], "max": [2]}
        ]
    });
    files.insert(
        PathBuf::from("valid/minimal-external/model.gltf"),
        json_bytes(&document)?,
    );
    files.insert(PathBuf::from("valid/minimal-external/mesh.bin"), bin);
    Ok(())
}

fn add_hierarchy_multiprimitive(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for value in [
        -1.0_f32, 0.0, -1.0, 1.0, 0.0, -1.0, 1.0, 0.0, 1.0, -1.0, 0.0, 1.0,
    ] {
        push_f32(&mut bin, value);
    }
    for index in [0_u16, 2, 1, 0, 3, 2] {
        push_u16(&mut bin, index);
    }
    align4(&mut bin, 0);
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [
            {"name": "ExactIntegerParent", "matrix": [1,0,0,0, 0,1,0,0, 0,0,1,0, 2,3,4,1], "children": [1,2]},
            {"name": "NegativeScaleChild", "translation": [1,2,3], "rotation": [0,0,0,1], "scale": [-2,3,0.5], "mesh": 0},
            {"name": "SecondInstance", "translation": [-2,0,1], "mesh": 0}
        ],
        "meshes": [{"name": "TwoPrimitiveQuad", "primitives": [
            {"attributes": {"POSITION": 0}, "indices": 1, "material": 0, "mode": 4},
            {"attributes": {"POSITION": 2}, "material": 1, "mode": 4}
        ]}],
        "materials": [
            {"name": "OpaqueRed", "pbrMetallicRoughness": {"baseColorFactor": [1,0,0,1], "metallicFactor": 0, "roughnessFactor": 1}},
            {"name": "OpaqueBlue", "pbrMetallicRoughness": {"baseColorFactor": [0,0,1,1], "metallicFactor": 0, "roughnessFactor": 1}}
        ],
        "buffers": [{"byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 48, "target": 34962},
            {"buffer": 0, "byteOffset": 48, "byteLength": 12, "target": 34963},
            {"buffer": 0, "byteOffset": 0, "byteLength": 36, "target": 34962}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]},
            {"bufferView": 1, "componentType": 5123, "count": 6, "type": "SCALAR"},
            {"bufferView": 2, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]}
        ]
    });
    files.insert(
        PathBuf::from("valid/hierarchy-multiprimitive/model.glb"),
        make_glb(&document, &bin)?,
    );
    Ok(())
}

fn add_primitive_modes(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for value in [
        -1.0_f32, 0.0, -1.0, 1.0, 0.0, -1.0, 1.0, 0.0, 1.0, -1.0, 0.0, 1.0, 0.0, 0.0, 2.0,
    ] {
        push_f32(&mut bin, value);
    }
    let positions_len = bin.len();
    bin.extend_from_slice(&[0, 2, 1]);
    let u8_offset = positions_len;
    align4(&mut bin, 0);
    let u16_offset = bin.len();
    for index in [0_u16, 1, 3, 2] {
        push_u16(&mut bin, index);
    }
    let u32_offset = bin.len();
    for index in [4_u32, 0, 1, 2, 3] {
        push_u32(&mut bin, index);
    }
    let uri = format!(
        "data:application/octet-stream;base64,{}",
        base64_encode(&bin)
    );
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "PrimitiveModes"}],
        "meshes": [{"primitives": [
            {"attributes": {"POSITION": 0}, "indices": 1, "mode": 4},
            {"attributes": {"POSITION": 0}, "indices": 2, "mode": 5},
            {"attributes": {"POSITION": 0}, "indices": 3, "mode": 6}
        ]}],
        "buffers": [{"uri": uri, "byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": positions_len, "target": 34962},
            {"buffer": 0, "byteOffset": u8_offset, "byteLength": 3, "target": 34963},
            {"buffer": 0, "byteOffset": u16_offset, "byteLength": 8, "target": 34963},
            {"buffer": 0, "byteOffset": u32_offset, "byteLength": 20, "target": 34963}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 5, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,2]},
            {"bufferView": 1, "componentType": 5121, "count": 3, "type": "SCALAR"},
            {"bufferView": 2, "componentType": 5123, "count": 4, "type": "SCALAR"},
            {"bufferView": 3, "componentType": 5125, "count": 5, "type": "SCALAR"}
        ]
    });
    files.insert(
        PathBuf::from("valid/primitive-modes/model.gltf"),
        json_bytes(&document)?,
    );
    Ok(())
}

fn add_accessor_layouts(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for (position, normal) in [
        ([-1.0_f32, 0.0, -1.0], [0.0_f32, 1.0, 0.0]),
        ([1.0, 0.0, -1.0], [0.0, 1.0, 0.0]),
        ([0.0, 0.0, 1.0], [0.0, 1.0, 0.0]),
    ] {
        for value in position {
            push_f32(&mut bin, value);
        }
        for value in normal {
            push_f32(&mut bin, value);
        }
    }
    let interleaved_len = bin.len();
    let uv_offset = bin.len();
    for value in [
        0.0_f32, 0.0, 1.0, 0.0, 0.5, 1.0, 0.25, 0.25, 0.75, 0.25, 0.5, 0.75,
    ] {
        push_f32(&mut bin, value);
    }
    let color_offset = bin.len();
    bin.extend_from_slice(&[255, 0, 128, 255, 0, 255, 0, 255, 128, 0, 255, 255]);
    let sparse_index_offset = bin.len();
    bin.push(2);
    align4(&mut bin, 0);
    let sparse_value_offset = bin.len();
    for value in [0.0_f32, 0.25, 1.5] {
        push_f32(&mut bin, value);
    }
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "AccessorLayouts"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0, "NORMAL": 1, "TEXCOORD_0": 2, "TEXCOORD_1": 3, "COLOR_0": 4}, "mode": 4}]}],
        "buffers": [{"byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": interleaved_len, "byteStride": 24, "target": 34962},
            {"buffer": 0, "byteOffset": uv_offset, "byteLength": 48, "byteStride": 8, "target": 34962},
            {"buffer": 0, "byteOffset": color_offset, "byteLength": 12, "target": 34962},
            {"buffer": 0, "byteOffset": sparse_index_offset, "byteLength": 1},
            {"buffer": 0, "byteOffset": sparse_value_offset, "byteLength": 12}
        ],
        "accessors": [
            {"bufferView": 0, "byteOffset": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0.25,1.5],
             "sparse": {"count": 1, "indices": {"bufferView": 3, "componentType": 5121}, "values": {"bufferView": 4}}},
            {"bufferView": 0, "byteOffset": 12, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "byteOffset": 0, "componentType": 5126, "count": 3, "type": "VEC2"},
            {"bufferView": 1, "byteOffset": 24, "componentType": 5126, "count": 3, "type": "VEC2"},
            {"bufferView": 2, "componentType": 5121, "normalized": true, "count": 3, "type": "VEC4"}
        ]
    });
    files.insert(
        PathBuf::from("valid/accessor-layouts/model.glb"),
        make_glb(&document, &bin)?,
    );
    Ok(())
}

fn add_material_textures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let (bin, position_view, uv_view, index_view) = textured_quad_buffer();
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "MaterialModes"}],
        "meshes": [{"primitives": [
            {"attributes": {"POSITION": 0, "TEXCOORD_0": 1, "TEXCOORD_1": 2}, "indices": 3, "material": 0},
            {"attributes": {"POSITION": 0, "TEXCOORD_0": 1, "TEXCOORD_1": 2}, "indices": 3, "material": 1},
            {"attributes": {"POSITION": 0, "TEXCOORD_0": 1, "TEXCOORD_1": 2}, "indices": 3, "material": 2}
        ]}],
        "materials": [
            {"name": "Opaque", "pbrMetallicRoughness": {"baseColorFactor": [0.8,0.7,0.6,1], "baseColorTexture": {"index": 0, "texCoord": 0}, "metallicFactor": 0, "roughnessFactor": 1}},
            {"name": "Mask", "alphaMode": "MASK", "alphaCutoff": 0.375, "doubleSided": true, "pbrMetallicRoughness": {"baseColorTexture": {"index": 1, "texCoord": 1}, "metallicFactor": 0, "roughnessFactor": 1}},
            {"name": "Blend", "alphaMode": "BLEND", "pbrMetallicRoughness": {"baseColorTexture": {"index": 0}, "metallicFactor": 0, "roughnessFactor": 1}}
        ],
        "samplers": [
            {"magFilter": 9728, "minFilter": 9984, "wrapS": 33071, "wrapT": 33071},
            {"magFilter": 9729, "minFilter": 9987, "wrapS": 10497, "wrapT": 33648}
        ],
        "images": [{"uri": "checker.png", "name": "Checker"}],
        "textures": [{"source": 0, "sampler": 0}, {"source": 0, "sampler": 1}],
        "buffers": [{"uri": "mesh.bin", "byteLength": bin.len()}],
        "bufferViews": [position_view, uv_view, index_view],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]},
            {"bufferView": 1, "byteOffset": 0, "componentType": 5126, "count": 4, "type": "VEC2"},
            {"bufferView": 1, "byteOffset": 32, "componentType": 5126, "count": 4, "type": "VEC2"},
            {"bufferView": 2, "componentType": 5123, "count": 6, "type": "SCALAR"}
        ]
    });
    files.insert(
        PathBuf::from("valid/material-textures/model.gltf"),
        json_bytes(&document)?,
    );
    files.insert(PathBuf::from("valid/material-textures/mesh.bin"), bin);
    files.insert(
        PathBuf::from("valid/material-textures/checker.png"),
        checker_png(),
    );
    Ok(())
}

fn add_embedded_texture(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let (mut bin, position_view, uv_view, index_view) = textured_quad_buffer();
    align4(&mut bin, 0);
    let image_offset = bin.len();
    let png = checker_png();
    bin.extend_from_slice(&png);
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "EmbeddedTexture"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0, "TEXCOORD_0": 1}, "indices": 2, "material": 0}]}],
        "materials": [{"pbrMetallicRoughness": {"baseColorTexture": {"index": 0}, "metallicFactor": 0, "roughnessFactor": 1}}],
        "images": [{"bufferView": 3, "mimeType": "image/png"}],
        "textures": [{"source": 0}],
        "buffers": [{"byteLength": bin.len()}],
        "bufferViews": [position_view, uv_view, index_view, {"buffer": 0, "byteOffset": image_offset, "byteLength": png.len()}],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]},
            {"bufferView": 1, "componentType": 5126, "count": 4, "type": "VEC2"},
            {"bufferView": 2, "componentType": 5123, "count": 6, "type": "SCALAR"}
        ]
    });
    files.insert(
        PathBuf::from("valid/embedded-texture/model.glb"),
        make_glb(&document, &bin)?,
    );
    Ok(())
}

fn add_collision_fixtures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for value in [
        -2.0_f32, 0.0, -2.0, 2.0, 0.0, -2.0, 2.0, 0.0, 2.0, -2.0, 0.0, 2.0, -1.5, 0.1, -1.5, 1.5,
        0.1, -1.5, 0.0, 0.1, 1.5, 0.0, 0.0, -2.0, 0.0, 3.0, -2.0, 0.0, 0.0, 2.0,
    ] {
        push_f32(&mut bin, value);
    }
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0,1,2]}],
        "nodes": [
            {"name": "RenderPlatform", "mesh": 0},
            {"name": "COL_ground", "mesh": 1, "translation": [0,0.25,0]},
            {"name": "COL_wall", "mesh": 2}
        ],
        "meshes": [
            {"name": "Render", "primitives": [{"attributes": {"POSITION": 0}, "mode": 5}]},
            {"name": "GroundCollision", "primitives": [{"attributes": {"POSITION": 1}, "mode": 4}]},
            {"name": "WallCollision", "primitives": [{"attributes": {"POSITION": 2}, "mode": 4}]}
        ],
        "buffers": [{"byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 48},
            {"buffer": 0, "byteOffset": 48, "byteLength": 36},
            {"buffer": 0, "byteOffset": 84, "byteLength": 36}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3", "min": [-2,0,-2], "max": [2,0,2]},
            {"bufferView": 1, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1.5,0.1,-1.5], "max": [1.5,0.1,1.5]},
            {"bufferView": 2, "componentType": 5126, "count": 3, "type": "VEC3", "min": [0,0,-2], "max": [0,3,2]}
        ]
    });
    files.insert(
        PathBuf::from("valid/collision-nodes/model.glb"),
        make_glb(&document, &bin)?,
    );

    let mut separate = Vec::new();
    for value in [-3.0_f32, 0.0, -3.0, 3.0, 0.0, -3.0, 0.0, 0.0, 3.0] {
        push_f32(&mut separate, value);
    }
    let separate_document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "SeparateCollision", "mesh": 0, "translation": [4,1,-2], "scale": [2,1,2]}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "mode": 4}]}],
        "buffers": [{"byteLength": separate.len()}],
        "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": separate.len()}],
        "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-3,0,-3], "max": [3,0,3]}]
    });
    files.insert(
        PathBuf::from("valid/collision-separate/model.glb"),
        make_glb(&separate_document, &separate)?,
    );
    Ok(())
}

fn add_pbr_diagnostics(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let mut bin = Vec::new();
    for value in [-1.0_f32, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0] {
        push_f32(&mut bin, value);
    }
    let normal_offset = bin.len();
    for value in [0.0_f32, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0] {
        push_f32(&mut bin, value);
    }
    let tangent_offset = bin.len();
    for value in [
        1.0_f32, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0,
    ] {
        push_f32(&mut bin, value);
    }
    let uv_offset = bin.len();
    for value in [0.0_f32, 0.0, 1.0, 0.0, 0.5, 1.0] {
        push_f32(&mut bin, value);
    }
    align4(&mut bin, 0);
    let image_offset = bin.len();
    let png = checker_png();
    bin.extend_from_slice(&png);
    let document = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "PbrDiagnostics"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0, "NORMAL": 1, "TANGENT": 2, "TEXCOORD_0": 3}, "material": 0}]}],
        "materials": [{
            "name": "EveryUnmappedInput",
            "pbrMetallicRoughness": {"baseColorTexture": {"index": 0}, "metallicFactor": 0.75, "roughnessFactor": 0.25, "metallicRoughnessTexture": {"index": 0}},
            "normalTexture": {"index": 0, "scale": 0.5},
            "occlusionTexture": {"index": 0, "strength": 0.6},
            "emissiveTexture": {"index": 0},
            "emissiveFactor": [0.2,0.3,0.4]
        }],
        "images": [{"bufferView": 4, "mimeType": "image/png"}],
        "textures": [{"source": 0}],
        "buffers": [{"byteLength": bin.len()}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36, "target": 34962},
            {"buffer": 0, "byteOffset": normal_offset, "byteLength": 36, "target": 34962},
            {"buffer": 0, "byteOffset": tangent_offset, "byteLength": 48, "target": 34962},
            {"buffer": 0, "byteOffset": uv_offset, "byteLength": 24, "target": 34962},
            {"buffer": 0, "byteOffset": image_offset, "byteLength": png.len()}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]},
            {"bufferView": 1, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 2, "componentType": 5126, "count": 3, "type": "VEC4"},
            {"bufferView": 3, "componentType": 5126, "count": 3, "type": "VEC2"}
        ]
    });
    files.insert(
        PathBuf::from("valid/pbr-diagnostics/model.glb"),
        make_glb(&document, &bin)?,
    );
    Ok(())
}

fn add_name_fixtures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let valid = named_triangle_scene(&[
        "ASCII_Model",
        "\u{30e2}\u{30c7}\u{30eb}",
        "\u{5730}\u{9762}",
    ]);
    files.insert(PathBuf::from("valid/names/model.gltf"), json_bytes(&valid)?);
    let rejected = named_triangle_scene(&["Valid", "Emoji_\u{1f31e}"]);
    files.insert(
        PathBuf::from("rejected/unencodable-name/model.gltf"),
        json_bytes(&rejected)?,
    );
    Ok(())
}

fn named_triangle_scene(names: &[&str]) -> Value {
    let (uri, byte_length) = triangle_data_uri_parts();
    json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": (0..names.len()).collect::<Vec<_>>() }],
        "nodes": names.iter().map(|name| json!({"name": name, "mesh": 0})).collect::<Vec<_>>(),
        "meshes": [{"name": "NamedTriangle", "primitives": [{"attributes": {"POSITION": 0}}]}],
        "buffers": [{"uri": uri, "byteLength": byte_length}],
        "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": 36, "target": 34962}],
        "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]}]
    })
}

fn add_unsupported_fixtures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let base = triangle_data_uri_parts();
    let skin = json!({
        "asset": {"version": "2.0", "generator": "sms-xtask"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "SkinnedMesh", "mesh": 0, "skin": 0}, {"name": "Joint"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}}]}],
        "skins": [{"joints": [1]}],
        "animations": [{"samplers": [{"input": 1, "output": 2}], "channels": [{"sampler": 0, "target": {"node": 1, "path": "translation"}}]}],
        "buffers": [{"uri": base.0, "byteLength": base.1}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 8},
            {"buffer": 0, "byteOffset": 44, "byteLength": 24}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]},
            {"bufferView": 1, "componentType": 5126, "count": 2, "type": "SCALAR", "min": [0], "max": [1]},
            {"bufferView": 2, "componentType": 5126, "count": 2, "type": "VEC3"}
        ]
    });
    files.insert(
        PathBuf::from("unsupported/skin-animation/model.gltf"),
        json_bytes(&skin)?,
    );

    let morph = json!({
        "asset": {"version": "2.0"}, "scene": 0, "scenes": [{"nodes": [0]}], "nodes": [{"mesh": 0}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "targets": [{"POSITION": 0}]}]}],
        "buffers": [{"uri": base.0, "byteLength": base.1}], "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": 36}],
        "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]}]
    });
    files.insert(
        PathBuf::from("unsupported/morph-target/model.gltf"),
        json_bytes(&morph)?,
    );
    for (name, mode) in [("lines", 1), ("points", 0)] {
        let document = json!({
            "asset": {"version": "2.0"}, "scene": 0, "scenes": [{"nodes": [0]}], "nodes": [{"mesh": 0}],
            "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "mode": mode}]}],
            "buffers": [{"uri": base.0, "byteLength": base.1}], "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": 36}],
            "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [-1,0,-1], "max": [1,0,1]}]
        });
        files.insert(
            PathBuf::from(format!("unsupported/{name}/model.gltf")),
            json_bytes(&document)?,
        );
    }
    Ok(())
}

fn add_security_fixtures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    for (name, uri) in [
        ("network-uri", "https://example.invalid/mesh.bin"),
        ("path-traversal", "../../outside.bin"),
    ] {
        let document = json!({
            "asset": {"version": "2.0"},
            "buffers": [{"uri": uri, "byteLength": 36}],
            "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": 36}],
            "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"}],
            "meshes": [{"primitives": [{"attributes": {"POSITION": 0}}]}],
            "nodes": [{"mesh": 0}], "scenes": [{"nodes": [0]}], "scene": 0
        });
        files.insert(
            PathBuf::from(format!("security/{name}/model.gltf")),
            json_bytes(&document)?,
        );
    }
    Ok(())
}

fn add_invalid_fixtures(files: &mut BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let oob = json!({
        "asset": {"version": "2.0"}, "buffers": [{"uri": "data:application/octet-stream;base64,AAAAAA==", "byteLength": 4}],
        "bufferViews": [{"buffer": 0, "byteOffset": 0, "byteLength": 4}],
        "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}}]}], "nodes": [{"mesh": 0}], "scenes": [{"nodes": [0]}], "scene": 0
    });
    files.insert(
        PathBuf::from("invalid/accessor-out-of-bounds/model.gltf"),
        json_bytes(&oob)?,
    );
    let missing = json!({
        "asset": {"version": "2.0"}, "buffers": [{"uri": "missing.bin", "byteLength": 36}],
        "bufferViews": [{"buffer": 0, "byteLength": 36}], "accessors": [{"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}}]}], "nodes": [{"mesh": 0}], "scenes": [{"nodes": [0]}], "scene": 0
    });
    files.insert(
        PathBuf::from("invalid/missing-external/model.gltf"),
        json_bytes(&missing)?,
    );
    files.insert(
        PathBuf::from("invalid/malformed-glb/model.glb"),
        b"glTF\x02\x00\x00\x00\x10\x00\x00\x00bad!".to_vec(),
    );
    Ok(())
}

fn textured_quad_buffer() -> (Vec<u8>, Value, Value, Value) {
    let mut bin = Vec::new();
    for value in [
        -1.0_f32, 0.0, -1.0, 1.0, 0.0, -1.0, 1.0, 0.0, 1.0, -1.0, 0.0, 1.0,
    ] {
        push_f32(&mut bin, value);
    }
    let uv_offset = bin.len();
    for value in [
        0.0_f32, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.25, 0.25, 0.75, 0.25, 0.75, 0.75, 0.25, 0.75,
    ] {
        push_f32(&mut bin, value);
    }
    let index_offset = bin.len();
    for index in [0_u16, 2, 1, 0, 3, 2] {
        push_u16(&mut bin, index);
    }
    align4(&mut bin, 0);
    (
        bin,
        json!({"buffer": 0, "byteOffset": 0, "byteLength": 48, "target": 34962}),
        json!({"buffer": 0, "byteOffset": uv_offset, "byteLength": 64, "byteStride": 8, "target": 34962}),
        json!({"buffer": 0, "byteOffset": index_offset, "byteLength": 12, "target": 34963}),
    )
}

fn triangle_data_uri_parts() -> (String, usize) {
    let mut bin = Vec::new();
    for value in [-1.0_f32, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0] {
        push_f32(&mut bin, value);
    }
    for value in [0.0_f32, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0] {
        push_f32(&mut bin, value);
    }
    let len = bin.len();
    (
        format!(
            "data:application/octet-stream;base64,{}",
            base64_encode(&bin)
        ),
        len,
    )
}

fn json_bytes(value: &Value) -> Result<Vec<u8>, String> {
    let mut bytes = serde_json::to_vec_pretty(value).map_err(|error| error.to_string())?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn make_glb(value: &Value, bin: &[u8]) -> Result<Vec<u8>, String> {
    let mut json = serde_json::to_vec(value).map_err(|error| error.to_string())?;
    align4(&mut json, b' ');
    let mut payload = bin.to_vec();
    align4(&mut payload, 0);
    let total_len = 12_usize
        .checked_add(8 + json.len())
        .and_then(|value| value.checked_add(8 + payload.len()))
        .ok_or_else(|| "GLB fixture length overflow".to_string())?;
    let total_len = u32::try_from(total_len).map_err(|_| "GLB fixture exceeds u32".to_string())?;
    let mut bytes = Vec::with_capacity(total_len as usize);
    bytes.extend_from_slice(&0x4654_6c67_u32.to_le_bytes());
    bytes.extend_from_slice(&2_u32.to_le_bytes());
    bytes.extend_from_slice(&total_len.to_le_bytes());
    bytes.extend_from_slice(&(json.len() as u32).to_le_bytes());
    bytes.extend_from_slice(&0x4e4f_534a_u32.to_le_bytes());
    bytes.extend_from_slice(&json);
    bytes.extend_from_slice(&(payload.len() as u32).to_le_bytes());
    bytes.extend_from_slice(&0x004e_4942_u32.to_le_bytes());
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

fn checker_png() -> Vec<u8> {
    let raw = [
        0, 255, 255, 255, 255, 20, 40, 220, 255, 0, 20, 40, 220, 128, 255, 255, 255, 0,
    ];
    let mut zlib = vec![0x78, 0x01, 0x01];
    let len = raw.len() as u16;
    zlib.extend_from_slice(&len.to_le_bytes());
    zlib.extend_from_slice(&(!len).to_le_bytes());
    zlib.extend_from_slice(&raw);
    zlib.extend_from_slice(&adler32(&raw).to_be_bytes());

    let mut png = b"\x89PNG\r\n\x1a\n".to_vec();
    let mut ihdr = Vec::new();
    ihdr.extend_from_slice(&2_u32.to_be_bytes());
    ihdr.extend_from_slice(&2_u32.to_be_bytes());
    ihdr.extend_from_slice(&[8, 6, 0, 0, 0]);
    png_chunk(&mut png, b"IHDR", &ihdr);
    png_chunk(&mut png, b"IDAT", &zlib);
    png_chunk(&mut png, b"IEND", &[]);
    png
}

fn png_chunk(png: &mut Vec<u8>, kind: &[u8; 4], data: &[u8]) {
    png.extend_from_slice(&(data.len() as u32).to_be_bytes());
    png.extend_from_slice(kind);
    png.extend_from_slice(data);
    let mut crc_input = kind.to_vec();
    crc_input.extend_from_slice(data);
    png.extend_from_slice(&crc32(&crc_input).to_be_bytes());
}

fn crc32(bytes: &[u8]) -> u32 {
    let mut crc = 0xffff_ffff_u32;
    for byte in bytes {
        crc ^= u32::from(*byte);
        for _ in 0..8 {
            let mask = (crc & 1).wrapping_neg();
            crc = (crc >> 1) ^ (0xedb8_8320 & mask);
        }
    }
    !crc
}

fn adler32(bytes: &[u8]) -> u32 {
    let mut a = 1_u32;
    let mut b = 0_u32;
    for byte in bytes {
        a = (a + u32::from(*byte)) % 65_521;
        b = (b + a) % 65_521;
    }
    (b << 16) | a
}

fn base64_encode(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut output = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let first = chunk[0];
        let second = chunk.get(1).copied().unwrap_or(0);
        let third = chunk.get(2).copied().unwrap_or(0);
        output.push(TABLE[usize::from(first >> 2)] as char);
        output.push(TABLE[usize::from((first & 0x03) << 4 | second >> 4)] as char);
        output.push(if chunk.len() >= 2 {
            TABLE[usize::from((second & 0x0f) << 2 | third >> 6)] as char
        } else {
            '='
        });
        output.push(if chunk.len() == 3 {
            TABLE[usize::from(third & 0x3f)] as char
        } else {
            '='
        });
    }
    output
}

fn push_f32(bytes: &mut Vec<u8>, value: f32) {
    bytes.extend_from_slice(&value.to_le_bytes());
}

fn push_u16(bytes: &mut Vec<u8>, value: u16) {
    bytes.extend_from_slice(&value.to_le_bytes());
}

fn push_u32(bytes: &mut Vec<u8>, value: u32) {
    bytes.extend_from_slice(&value.to_le_bytes());
}

fn align4(bytes: &mut Vec<u8>, padding: u8) {
    while !bytes.len().is_multiple_of(4) {
        bytes.push(padding);
    }
}

fn write_files(root: &Path, expected: &BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    fs::create_dir_all(root).map_err(|error| format!("create {}: {error}", root.display()))?;
    let existing = existing_files(root)?;
    for stale in existing.difference(&expected.keys().cloned().collect()) {
        let path = root.join(stale);
        fs::remove_file(&path)
            .map_err(|error| format!("remove stale {}: {error}", path.display()))?;
    }
    for (relative, bytes) in expected {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("create {}: {error}", parent.display()))?;
        }
        fs::write(&path, bytes).map_err(|error| format!("write {}: {error}", path.display()))?;
    }
    Ok(())
}

fn check_files(root: &Path, expected: &BTreeMap<PathBuf, Vec<u8>>) -> Result<(), String> {
    let actual_paths = existing_files(root)?;
    let expected_paths = expected.keys().cloned().collect::<BTreeSet<_>>();
    if actual_paths != expected_paths {
        let missing = expected_paths.difference(&actual_paths).collect::<Vec<_>>();
        let stale = actual_paths.difference(&expected_paths).collect::<Vec<_>>();
        return Err(format!(
            "glTF fixture inventory drifted; missing={missing:?}, stale={stale:?}"
        ));
    }
    for (relative, expected_bytes) in expected {
        let path = root.join(relative);
        let actual =
            fs::read(&path).map_err(|error| format!("read {}: {error}", path.display()))?;
        if actual != *expected_bytes {
            return Err(format!("glTF fixture is stale: {}", path.display()));
        }
    }
    Ok(())
}

fn existing_files(root: &Path) -> Result<BTreeSet<PathBuf>, String> {
    if !root.is_dir() {
        return Ok(BTreeSet::new());
    }
    let mut pending = vec![root.to_path_buf()];
    let mut files = BTreeSet::new();
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(&directory)
            .map_err(|error| format!("read {}: {error}", directory.display()))?
        {
            let entry =
                entry.map_err(|error| format!("read {} entry: {error}", directory.display()))?;
            let file_type = entry
                .file_type()
                .map_err(|error| format!("stat {}: {error}", entry.path().display()))?;
            if file_type.is_dir() {
                pending.push(entry.path());
            } else if file_type.is_file() {
                files.insert(
                    entry
                        .path()
                        .strip_prefix(root)
                        .map_err(|error| error.to_string())?
                        .to_path_buf(),
                );
            } else {
                return Err(format!(
                    "unsupported fixture entry: {}",
                    entry.path().display()
                ));
            }
        }
    }
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_generation_is_byte_deterministic() {
        assert_eq!(fixture_files().unwrap(), fixture_files().unwrap());
    }

    #[test]
    fn generated_glbs_have_canonical_headers_and_lengths() {
        for (path, bytes) in fixture_files().unwrap() {
            if path.extension().and_then(OsStr::to_str) != Some("glb")
                || path.starts_with("invalid")
            {
                continue;
            }
            assert_eq!(&bytes[..4], b"glTF", "{}", path.display());
            assert_eq!(u32::from_le_bytes(bytes[4..8].try_into().unwrap()), 2);
            assert_eq!(
                u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize,
                bytes.len()
            );
            assert_eq!(bytes.len() % 4, 0);
        }
    }

    #[test]
    fn generated_checker_is_a_png() {
        let png = checker_png();
        assert_eq!(&png[..8], b"\x89PNG\r\n\x1a\n");
    }

    #[test]
    fn committed_fixtures_are_current() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(Path::parent)
            .unwrap();
        check(repo_root).unwrap();
    }
}
